/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.iup.chem.inventory.wizard;

import java.util.Calendar;
import java.util.List;

import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.ListSelectionModel;

import org.ciscavate.cjwizard.WizardPage;
import org.ciscavate.cjwizard.WizardSettings;
import org.jdesktop.swingx.JXDatePicker;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import org.jdesktop.swingx.combobox.ListComboBoxModel;
import org.jdesktop.swingx.renderer.DefaultListRenderer;
import org.jdesktop.swingx.renderer.StringValue;
import org.jdesktop.swingx.renderer.StringValues;

import edu.iup.chem.inventory.dao.RoleDao;
import edu.iup.chem.inventory.dao.RoomDao;
import edu.iup.chem.inventory.db.inventory.tables.records.RoleRecord;
import edu.iup.chem.inventory.db.inventory.tables.records.RoomRecord;
import edu.iup.chem.inventory.db.inventory.tables.records.UserRecord;

/**
 * 
 * @author Zach
 */
public class NewUserWizardPage extends WizardPage {

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JTextField		email;
	private JXDatePicker				expiration;
	private javax.swing.JLabel			jLabel1;
	private javax.swing.JLabel			jLabel2;
	private javax.swing.JLabel			jLabel3;
	private javax.swing.JLabel			jLabel4;
	private javax.swing.JLabel			jLabel5;
	private javax.swing.JLabel			jLabel6;
	private javax.swing.JLabel			jLabel7;
	private javax.swing.JScrollPane		jScrollPane1;
	private javax.swing.JTextField		name;
	private javax.swing.JPasswordField	password;
	private javax.swing.JComboBox		role;
	private javax.swing.JList			rooms;
	private javax.swing.JTextField		username;
	// End of variables declaration//GEN-END:variables
	private final WizardSettings		settings;

	public NewUserWizardPage(final WizardSettings settings) {
		super("Create New User", "Enter information for the new user.");
		this.settings = settings;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		username = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		password = new javax.swing.JPasswordField();
		jLabel2 = new javax.swing.JLabel();
		email = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		name = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jLabel6 = new javax.swing.JLabel();
		final Calendar cal = Calendar.getInstance();
		cal.add(Calendar.YEAR, 4);
		expiration = new JXDatePicker(cal.getTime());
		expiration.setName("expiration");
		jLabel7 = new javax.swing.JLabel();

		jLabel1.setLabelFor(username);
		jLabel1.setText("Username:");

		jLabel2.setLabelFor(password);
		jLabel2.setText("Password:");

		jLabel3.setLabelFor(email);
		jLabel3.setText("Email:");

		jLabel4.setText("Name:");

		jLabel7.setLabelFor(expiration);
		jLabel7.setText("User expires:");

		final ListComboBoxModel<RoleRecord> roleModel = new ListComboBoxModel<>(
				RoleDao.getRoles());
		role = new JComboBox<>(roleModel);
		role.setRenderer(new DefaultListRenderer(new StringValue() {
			@Override
			public String getString(final Object value) {
				if (value instanceof RoleRecord) {
					return ((RoleRecord) value).getName();
				}

				return StringValues.TO_STRING.getString(value);
			}
		}));
		AutoCompleteDecorator.decorate(role);

		jLabel5.setText("Role:");

		final List<RoomRecord> roomList = RoomDao.getAllRoomRecords();
		rooms = new JList<>(roomList.toArray(new RoomRecord[roomList.size()]));
		rooms.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
		jScrollPane1.setViewportView(rooms);

		jLabel6.setText("Select rooms to assign (or primary room(s) for admins): ");

		email.setName("email");
		name.setName("name");
		password.setName("password");
		role.setName("role");
		rooms.setName("rooms");
		username.setName("username");

		if (settings.get("user") != null) {
			final UserRecord user = (UserRecord) settings.get("user");
			name.setText(user.getName());
			password.setEnabled(false);
			role.setSelectedItem(user.fetchRoleByRid());
			username.setText(user.getUsername());
			email.setText(user.getEmail());
			final List<RoomRecord> userRooms = user.fetchUserRooms();
			// I'm going to hack this to make it select an unknown amount of
			// disjoint rooms, sorry
			final int[] indices = new int[userRooms.size()];
			int index = 0;
			for (final RoomRecord room : userRooms) {
				rooms.setSelectedValue(room, false);
				final int selected = rooms.getSelectedIndex();
				indices[index++] = selected;
			}

			rooms.clearSelection();
			rooms.setSelectedIndices(indices);
		}

		final javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(name)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jLabel4)
																.addGap(0,
																		0,
																		Short.MAX_VALUE))
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jLabel1)
																				.addComponent(
																						username,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						84,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jLabel2)
																				.addComponent(
																						password))))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jLabel5)
																				.addComponent(
																						role,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						125,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGap(93, 93,
																		93))
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						email,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						125,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jLabel3))
																.addGap(18, 18,
																		18)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jLabel7)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										expiration,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										77,
																										Short.MAX_VALUE)
																								.addGap(80,
																										80,
																										80))))))
				.addGroup(
						layout.createSequentialGroup()
								.addGap(113, 113, 113)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel6)
												.addComponent(
														jScrollPane1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														164,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(12, 12, 12)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel1)
												.addComponent(jLabel2)
												.addComponent(jLabel3)
												.addComponent(jLabel7))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														username,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														password,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														email,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														expiration,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel4)
												.addComponent(jLabel5))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														name,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														role,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addComponent(jLabel6)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(jScrollPane1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										147,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(21, 21, 21)));
	}// </editor-fold>//GEN-END:initComponents
}
