/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.iup.chem.inventory.wizard;

import java.util.Arrays;

import javax.swing.JComboBox;
import javax.swing.JOptionPane;

import org.apache.log4j.Logger;
import org.ciscavate.cjwizard.WizardPage;
import org.ciscavate.cjwizard.WizardSettings;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import org.jdesktop.swingx.combobox.ListComboBoxModel;
import org.jdesktop.swingx.renderer.DefaultListRenderer;
import org.jdesktop.swingx.renderer.StringValue;
import org.jdesktop.swingx.renderer.StringValues;

import edu.iup.chem.inventory.db.inventory.enums.ChemicalCarc;
import edu.iup.chem.inventory.db.inventory.enums.ChemicalCold;
import edu.iup.chem.inventory.db.inventory.enums.ChemicalFlamm;
import edu.iup.chem.inventory.db.inventory.enums.ChemicalNfpaS;
import edu.iup.chem.inventory.db.inventory.enums.ChemicalStorageClass;
import edu.iup.chem.inventory.db.inventory.enums.ChemicalToxic;
import edu.iup.chem.inventory.db.inventory.tables.records.ChemicalRecord;

/**
 * 
 * @author Zach
 */
public class VerifyChemicalFieldsWizardPage extends WizardPage {

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JCheckBox						carcCheck;

	private javax.swing.JCheckBox						coldCheck;

	private javax.swing.JCheckBox						flammCheck;

	private javax.swing.JTextField						formula;

	private javax.swing.JLabel							jLabel1;
	private javax.swing.JLabel							jLabel10;
	private javax.swing.JLabel							jLabel2;
	private javax.swing.JLabel							jLabel3;
	private javax.swing.JLabel							jLabel4;
	private javax.swing.JLabel							jLabel5;
	private javax.swing.JLabel							jLabel7;
	private javax.swing.JLabel							jLabel8;
	private javax.swing.JLabel							jLabel9;
	private javax.swing.JSeparator						jSeparator1;
	private javax.swing.JTextField						name;
	private javax.swing.JComboBox<Integer>				nfpaFCombo;
	private javax.swing.JComboBox<Integer>				nfpaHCombo;
	private javax.swing.JComboBox<Integer>				nfpaRCombo;
	private javax.swing.JComboBox<ChemicalNfpaS>		nfpaSCombo;
	private javax.swing.JTextField						smiles;
	private javax.swing.JComboBox<ChemicalStorageClass>	storageCombo;
	private javax.swing.JComboBox<ChemicalToxic>		toxicCombo;

	private final WizardSettings						settings;

	private static Logger								log	= Logger.getLogger(VerifyChemicalFieldsWizardPage.class);

	// End of variables declaration//GEN-END:variables
	/**
	 * Creates new form VerifyChemicalFieldsWizardPage
	 */
	public VerifyChemicalFieldsWizardPage(final WizardSettings settings) {
		super("Verify Fields",
				"Confirm contents of fields for the new chemical.");
		this.settings = settings;
		initComponents();
		final ChemicalRecord r = getNewRecord();
		if (r == null) {
			JOptionPane
					.showMessageDialog(this,
							"Could not find any chemicals with that CAS Number. Manually enter fields");
		} else {
			populateForm(r);
		}
	}

	private void coldCheckActionPerformed(final java.awt.event.ActionEvent evt) {// GEN-FIRST:event_coldCheckActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_coldCheckActionPerformed

	private void flammCheckActionPerformed(final java.awt.event.ActionEvent evt) {// GEN-FIRST:event_flammCheckActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_flammCheckActionPerformed

	private ChemicalRecord getNewRecord() {
		return (ChemicalRecord) settings.get("chemicalRecord");
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		final Integer[] numbers = { 0, 1, 2, 3, 4 };

		name = new javax.swing.JTextField();
		formula = new javax.swing.JTextField();
		smiles = new javax.swing.JTextField();
		jSeparator1 = new javax.swing.JSeparator();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		coldCheck = new javax.swing.JCheckBox();
		flammCheck = new javax.swing.JCheckBox();
		carcCheck = new javax.swing.JCheckBox();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		nfpaFCombo = new JComboBox<>(numbers);
		jLabel7 = new javax.swing.JLabel();
		nfpaHCombo = new JComboBox<>(numbers);
		jLabel8 = new javax.swing.JLabel();
		nfpaRCombo = new JComboBox<>(numbers);
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();

		name.setName("name"); // NOI18N

		formula.setName("formula"); // NOI18N

		smiles.setName("smiles"); // NOI18N

		jLabel1.setLabelFor(name);
		jLabel1.setText("Chemical Name");

		jLabel2.setLabelFor(formula);
		jLabel2.setText("Molecular Formula");

		jLabel3.setLabelFor(smiles);
		jLabel3.setText("SMILES String");

		coldCheck.setText("Needs Cold Storage?");
		coldCheck.setName("cold"); // NOI18N
		coldCheck.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(final java.awt.event.ActionEvent evt) {
				coldCheckActionPerformed(evt);
			}
		});

		flammCheck.setText("Is Flammable?");
		flammCheck.setName("flamm"); // NOI18N
		flammCheck.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(final java.awt.event.ActionEvent evt) {
				flammCheckActionPerformed(evt);
			}
		});

		carcCheck.setText("Is Carcinogenic?");
		carcCheck.setName("carc"); // NOI18N

		final ListComboBoxModel<ChemicalStorageClass> storageModel = new ListComboBoxModel<>(
				Arrays.asList(ChemicalStorageClass.values()));
		storageCombo = new JComboBox<>(storageModel);
		storageCombo.setRenderer(new DefaultListRenderer(new StringValue() {
			@Override
			public String getString(final Object value) {
				if (value instanceof ChemicalStorageClass) {
					return ((ChemicalStorageClass) value).getLiteral();
				}

				return StringValues.TO_STRING.getString(value);
			}
		}));
		AutoCompleteDecorator.decorate(storageCombo);

		storageCombo.setName("storage_class"); // NOI18N

		final ListComboBoxModel<ChemicalToxic> toxicModel = new ListComboBoxModel<>(
				Arrays.asList(ChemicalToxic.values()));
		toxicCombo = new JComboBox<>(toxicModel);
		toxicCombo.setRenderer(new DefaultListRenderer(new StringValue() {
			@Override
			public String getString(final Object value) {
				if (value instanceof ChemicalToxic) {
					return ((ChemicalToxic) value).getLiteral();
				}

				return StringValues.TO_STRING.getString(value);
			}
		}));
		AutoCompleteDecorator.decorate(toxicCombo);
		toxicCombo.setName("toxic"); // NOI18N

		jLabel4.setLabelFor(storageCombo);
		jLabel4.setText("Storage Class");

		jLabel5.setLabelFor(toxicCombo);
		jLabel5.setText("Toxicity Level");

		AutoCompleteDecorator.decorate(nfpaFCombo);
		nfpaFCombo.setName("nfpaf"); // NOI18N

		jLabel7.setLabelFor(nfpaFCombo);
		jLabel7.setText("NFPA Fire");

		AutoCompleteDecorator.decorate(nfpaHCombo);
		nfpaHCombo.setName("nfpah"); // NOI18N

		jLabel8.setLabelFor(nfpaHCombo);
		jLabel8.setText("NFPA Health");

		AutoCompleteDecorator.decorate(nfpaRCombo);
		nfpaRCombo.setName("nfpar"); // NOI18N

		jLabel9.setLabelFor(nfpaRCombo);
		jLabel9.setText("NFPA Reactivity");

		final ListComboBoxModel<ChemicalNfpaS> specModel = new ListComboBoxModel<>(
				Arrays.asList(ChemicalNfpaS.values()));
		final JComboBox<ChemicalNfpaS> specCombo = new JComboBox<>(specModel);
		specCombo.setRenderer(new DefaultListRenderer(new StringValue() {
			@Override
			public String getString(final Object value) {
				if (value instanceof ChemicalToxic) {
					return ((ChemicalToxic) value).getLiteral();
				}

				return StringValues.TO_STRING.getString(value);
			}
		}));
		AutoCompleteDecorator.decorate(specCombo);

		nfpaSCombo = specCombo;

		nfpaSCombo.setName("nfpas"); // NOI18N

		jLabel10.setLabelFor(nfpaSCombo);
		jLabel10.setText("NFPA Special");

		final javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addContainerGap()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jSeparator1)
																				.addGroup(
																						javax.swing.GroupLayout.Alignment.TRAILING,
																						layout.createSequentialGroup()
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addComponent(
																														name)
																												.addGroup(
																														layout.createSequentialGroup()
																																.addComponent(
																																		jLabel1)
																																.addGap(0,
																																		0,
																																		Short.MAX_VALUE)))
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addComponent(
																														formula,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														99,
																														javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addComponent(
																														jLabel2))
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addComponent(
																														jLabel3)
																												.addComponent(
																														smiles,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														161,
																														javax.swing.GroupLayout.PREFERRED_SIZE)))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addGroup(
																														layout.createSequentialGroup()
																																.addComponent(
																																		storageCombo,
																																		javax.swing.GroupLayout.PREFERRED_SIZE,
																																		javax.swing.GroupLayout.DEFAULT_SIZE,
																																		javax.swing.GroupLayout.PREFERRED_SIZE)
																																.addGap(87,
																																		87,
																																		87)
																																.addComponent(
																																		toxicCombo,
																																		javax.swing.GroupLayout.PREFERRED_SIZE,
																																		javax.swing.GroupLayout.DEFAULT_SIZE,
																																		javax.swing.GroupLayout.PREFERRED_SIZE))
																												.addGroup(
																														layout.createSequentialGroup()
																																.addGap(88,
																																		88,
																																		88)
																																.addGroup(
																																		layout.createParallelGroup(
																																				javax.swing.GroupLayout.Alignment.LEADING)
																																				.addComponent(
																																						nfpaHCombo,
																																						javax.swing.GroupLayout.PREFERRED_SIZE,
																																						javax.swing.GroupLayout.DEFAULT_SIZE,
																																						javax.swing.GroupLayout.PREFERRED_SIZE)
																																				.addComponent(
																																						jLabel8))
																																.addGap(86,
																																		86,
																																		86)
																																.addGroup(
																																		layout.createParallelGroup(
																																				javax.swing.GroupLayout.Alignment.LEADING)
																																				.addComponent(
																																						jLabel9)
																																				.addComponent(
																																						nfpaRCombo,
																																						javax.swing.GroupLayout.PREFERRED_SIZE,
																																						javax.swing.GroupLayout.DEFAULT_SIZE,
																																						javax.swing.GroupLayout.PREFERRED_SIZE)))
																												.addGroup(
																														layout.createSequentialGroup()
																																.addGroup(
																																		layout.createParallelGroup(
																																				javax.swing.GroupLayout.Alignment.LEADING)
																																				.addComponent(
																																						coldCheck)
																																				.addComponent(
																																						jLabel4))
																																.addGap(18,
																																		18,
																																		18)
																																.addGroup(
																																		layout.createParallelGroup(
																																				javax.swing.GroupLayout.Alignment.LEADING)
																																				.addComponent(
																																						flammCheck)
																																				.addComponent(
																																						jLabel5))
																																.addGap(18,
																																		18,
																																		18)
																																.addComponent(
																																		carcCheck)))
																								.addGap(17,
																										17,
																										17))))
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGap(170,
																										170,
																										170)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addComponent(
																														jLabel7)
																												.addComponent(
																														nfpaFCombo,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														javax.swing.GroupLayout.PREFERRED_SIZE)))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGap(169,
																										169,
																										169)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addComponent(
																														jLabel10)
																												.addComponent(
																														nfpaSCombo,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														javax.swing.GroupLayout.PREFERRED_SIZE))))
																.addGap(0,
																		0,
																		Short.MAX_VALUE)))
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(22, 22, 22)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel1)
												.addComponent(jLabel2)
												.addComponent(jLabel3))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														name,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														formula,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														smiles,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jSeparator1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										10,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(coldCheck)
												.addComponent(flammCheck)
												.addComponent(carcCheck))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jLabel4)
																				.addComponent(
																						jLabel5))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		toxicCombo,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(18, 18,
																		18)
																.addComponent(
																		jLabel7)
																.addGap(2, 2, 2)
																.addComponent(
																		nfpaFCombo,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jLabel8)
																				.addComponent(
																						jLabel9))
																.addGap(4, 4, 4)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						nfpaHCombo,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						nfpaRCombo,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(
																		jLabel10)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addComponent(
																		nfpaSCombo,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(21, 21,
																		21)
																.addComponent(
																		storageCombo,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(0,
																		0,
																		Short.MAX_VALUE)))
								.addContainerGap()));
	}// </editor-fold>//GEN-END:initComponents

	private void populateForm(final ChemicalRecord r) {
		name.setText(r.getName());
		formula.setText(r.getFormula());
		smiles.setText(r.getSmiles());

		if (r.getCarc().equals(ChemicalCarc.Yes)) {
			carcCheck.setSelected(true);
		}

		if (r.getCold().equals(ChemicalCold.Yes)) {
			coldCheck.setSelected(true);
		}

		if (r.getFlamm().equals(ChemicalFlamm.Yes)) {
			flammCheck.setSelected(true);
		}

		storageCombo.setSelectedItem(r.getStorageClass());
		toxicCombo.setSelectedItem(r.getToxic());

		nfpaHCombo.setSelectedIndex(r.getNfpaH());
		nfpaFCombo.setSelectedIndex(r.getNfpaF());
		nfpaRCombo.setSelectedIndex(r.getNfpaR());
		nfpaSCombo.setSelectedItem(r.getNfpaS());

	}

}
