/**
 * This class is generated by jOOQ
 */
package edu.iup.chem.inventory.db.inventory;

/**
 * This class is generated by jOOQ.
 * 
 * A class modelling foreign key relationships between tables of the
 * <code>inventory</code> schema
 */
@javax.annotation.Generated(value = { "http://www.jooq.org", "2.5.1" }, comments = "This class is generated by jOOQ")
public class Keys {

	@SuppressWarnings({ "hiding", "unchecked" })
	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<edu.iup.chem.inventory.db.inventory.tables.records.FieldDataFieldNameRecord, edu.iup.chem.inventory.db.inventory.tables.records.UsersRecord>	FIELD_DATA_FIELD_NAME_IBFK_1	= createForeignKey(
																																																										edu.iup.chem.inventory.db.inventory.Keys.KEY_USERS_PRIMARY,
																																																										edu.iup.chem.inventory.db.inventory.tables.FieldDataFieldName.FIELD_DATA_FIELD_NAME,
																																																										edu.iup.chem.inventory.db.inventory.tables.FieldDataFieldName.FIELD_DATA_FIELD_NAME.ENTITY_ID);
		public static final org.jooq.ForeignKey<edu.iup.chem.inventory.db.inventory.tables.records.FieldDataFieldRoomRecord, edu.iup.chem.inventory.db.inventory.tables.records.UsersRecord>	FIELD_DATA_FIELD_ROOM_IBFK_1	= createForeignKey(
																																																										edu.iup.chem.inventory.db.inventory.Keys.KEY_USERS_PRIMARY,
																																																										edu.iup.chem.inventory.db.inventory.tables.FieldDataFieldRoom.FIELD_DATA_FIELD_ROOM,
																																																										edu.iup.chem.inventory.db.inventory.tables.FieldDataFieldRoom.FIELD_DATA_FIELD_ROOM.ENTITY_ID);
		public static final org.jooq.ForeignKey<edu.iup.chem.inventory.db.inventory.tables.records.UserRecord, edu.iup.chem.inventory.db.inventory.tables.records.RoleRecord>					USER_IBFK_2						= createForeignKey(
																																																										edu.iup.chem.inventory.db.inventory.Keys.KEY_ROLE_PRIMARY,
																																																										edu.iup.chem.inventory.db.inventory.tables.User.USER,
																																																										edu.iup.chem.inventory.db.inventory.tables.User.USER.RID);
		public static final org.jooq.ForeignKey<edu.iup.chem.inventory.db.inventory.tables.records.UserRecord, edu.iup.chem.inventory.db.inventory.tables.records.RoleRecord>					USER_IBFK_3						= createForeignKey(
																																																										edu.iup.chem.inventory.db.inventory.Keys.KEY_ROLE_NAME,
																																																										edu.iup.chem.inventory.db.inventory.tables.User.USER,
																																																										edu.iup.chem.inventory.db.inventory.tables.User.USER.ROLE_NAME);
		public static final org.jooq.ForeignKey<edu.iup.chem.inventory.db.inventory.tables.records.UserRecord, edu.iup.chem.inventory.db.inventory.tables.records.RoomRecord>					USER_IBFK_1						= createForeignKey(
																																																										edu.iup.chem.inventory.db.inventory.Keys.KEY_ROOM_PRIMARY,
																																																										edu.iup.chem.inventory.db.inventory.tables.User.USER,
																																																										edu.iup.chem.inventory.db.inventory.tables.User.USER.ROOM);
	}

	@SuppressWarnings("hiding")
	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<edu.iup.chem.inventory.db.inventory.tables.records.AccessRecord, java.lang.Integer>					IDENTITY_ACCESS			= createIdentity(
																																											edu.iup.chem.inventory.db.inventory.tables.Access.ACCESS,
																																											edu.iup.chem.inventory.db.inventory.tables.Access.ACCESS.RID);
		public static org.jooq.Identity<edu.iup.chem.inventory.db.inventory.tables.records.LocationRecord, java.lang.Integer>				IDENTITY_LOCATION		= createIdentity(
																																											edu.iup.chem.inventory.db.inventory.tables.Location.LOCATION,
																																											edu.iup.chem.inventory.db.inventory.tables.Location.LOCATION.BOTTLE_NO);
		public static org.jooq.Identity<edu.iup.chem.inventory.db.inventory.tables.records.RoleRecord, org.jooq.tools.unsigned.UInteger>	IDENTITY_ROLE			= createIdentity(
																																											edu.iup.chem.inventory.db.inventory.tables.Role.ROLE,
																																											edu.iup.chem.inventory.db.inventory.tables.Role.ROLE.RID);
		public static org.jooq.Identity<edu.iup.chem.inventory.db.inventory.tables.records.StructuresRecord, java.lang.Integer>				IDENTITY_STRUCTURES		= createIdentity(
																																											edu.iup.chem.inventory.db.inventory.tables.Structures.STRUCTURES,
																																											edu.iup.chem.inventory.db.inventory.tables.Structures.STRUCTURES.CD_ID);
		public static org.jooq.Identity<edu.iup.chem.inventory.db.inventory.tables.records.StructuresUlRecord, java.lang.Integer>			IDENTITY_STRUCTURES_UL	= createIdentity(
																																											edu.iup.chem.inventory.db.inventory.tables.StructuresUl.STRUCTURES_UL,
																																											edu.iup.chem.inventory.db.inventory.tables.StructuresUl.STRUCTURES_UL.UPDATE_ID);
		public static org.jooq.Identity<edu.iup.chem.inventory.db.inventory.tables.records.UserRecord, java.lang.Integer>					IDENTITY_USER			= createIdentity(
																																											edu.iup.chem.inventory.db.inventory.tables.User.USER,
																																											edu.iup.chem.inventory.db.inventory.tables.User.USER.UID);
		public static org.jooq.Identity<edu.iup.chem.inventory.db.inventory.tables.records.ChemicalRecord, java.lang.Integer>				IDENTITY_CHEMICAL		= createIdentity(
																																											edu.iup.chem.inventory.db.inventory.tables.Chemical.CHEMICAL,
																																											edu.iup.chem.inventory.db.inventory.tables.Chemical.CHEMICAL.CID);

	}

	@SuppressWarnings({ "hiding", "unchecked" })
	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<edu.iup.chem.inventory.db.inventory.tables.records.AccessRecord>				KEY_ACCESS_PRIMARY					= createUniqueKey(
																																										edu.iup.chem.inventory.db.inventory.tables.Access.ACCESS,
																																										edu.iup.chem.inventory.db.inventory.tables.Access.ACCESS.RID);
		public static final org.jooq.UniqueKey<edu.iup.chem.inventory.db.inventory.tables.records.ChemicalRecord>			KEY_CHEMICAL_PRIMARY				= createUniqueKey(
																																										edu.iup.chem.inventory.db.inventory.tables.Chemical.CHEMICAL,
																																										edu.iup.chem.inventory.db.inventory.tables.Chemical.CHEMICAL.CID);
		public static final org.jooq.UniqueKey<edu.iup.chem.inventory.db.inventory.tables.records.FieldDataFieldNameRecord>	KEY_FIELD_DATA_FIELD_NAME_PRIMARY	= createUniqueKey(
																																										edu.iup.chem.inventory.db.inventory.tables.FieldDataFieldName.FIELD_DATA_FIELD_NAME,
																																										edu.iup.chem.inventory.db.inventory.tables.FieldDataFieldName.FIELD_DATA_FIELD_NAME.ENTITY_TYPE,
																																										edu.iup.chem.inventory.db.inventory.tables.FieldDataFieldName.FIELD_DATA_FIELD_NAME.ENTITY_ID,
																																										edu.iup.chem.inventory.db.inventory.tables.FieldDataFieldName.FIELD_DATA_FIELD_NAME.DELETED,
																																										edu.iup.chem.inventory.db.inventory.tables.FieldDataFieldName.FIELD_DATA_FIELD_NAME.DELTA,
																																										edu.iup.chem.inventory.db.inventory.tables.FieldDataFieldName.FIELD_DATA_FIELD_NAME.LANGUAGE);
		public static final org.jooq.UniqueKey<edu.iup.chem.inventory.db.inventory.tables.records.FieldDataFieldRoomRecord>	KEY_FIELD_DATA_FIELD_ROOM_PRIMARY	= createUniqueKey(
																																										edu.iup.chem.inventory.db.inventory.tables.FieldDataFieldRoom.FIELD_DATA_FIELD_ROOM,
																																										edu.iup.chem.inventory.db.inventory.tables.FieldDataFieldRoom.FIELD_DATA_FIELD_ROOM.ENTITY_TYPE,
																																										edu.iup.chem.inventory.db.inventory.tables.FieldDataFieldRoom.FIELD_DATA_FIELD_ROOM.ENTITY_ID,
																																										edu.iup.chem.inventory.db.inventory.tables.FieldDataFieldRoom.FIELD_DATA_FIELD_ROOM.DELETED,
																																										edu.iup.chem.inventory.db.inventory.tables.FieldDataFieldRoom.FIELD_DATA_FIELD_ROOM.DELTA,
																																										edu.iup.chem.inventory.db.inventory.tables.FieldDataFieldRoom.FIELD_DATA_FIELD_ROOM.LANGUAGE);
		public static final org.jooq.UniqueKey<edu.iup.chem.inventory.db.inventory.tables.records.JchempropertiesRecord>	KEY_JCHEMPROPERTIES_PRIMARY			= createUniqueKey(
																																										edu.iup.chem.inventory.db.inventory.tables.Jchemproperties.JCHEMPROPERTIES,
																																										edu.iup.chem.inventory.db.inventory.tables.Jchemproperties.JCHEMPROPERTIES.PROP_NAME);
		public static final org.jooq.UniqueKey<edu.iup.chem.inventory.db.inventory.tables.records.JchempropertiesCrRecord>	KEY_JCHEMPROPERTIES_CR_PRIMARY		= createUniqueKey(
																																										edu.iup.chem.inventory.db.inventory.tables.JchempropertiesCr.JCHEMPROPERTIES_CR,
																																										edu.iup.chem.inventory.db.inventory.tables.JchempropertiesCr.JCHEMPROPERTIES_CR.CACHE_ID);
		public static final org.jooq.UniqueKey<edu.iup.chem.inventory.db.inventory.tables.records.LocationRecord>			KEY_LOCATION_PRIMARY				= createUniqueKey(
																																										edu.iup.chem.inventory.db.inventory.tables.Location.LOCATION,
																																										edu.iup.chem.inventory.db.inventory.tables.Location.LOCATION.BOTTLE_NO);
		public static final org.jooq.UniqueKey<edu.iup.chem.inventory.db.inventory.tables.records.RoleRecord>				KEY_ROLE_PRIMARY					= createUniqueKey(
																																										edu.iup.chem.inventory.db.inventory.tables.Role.ROLE,
																																										edu.iup.chem.inventory.db.inventory.tables.Role.ROLE.RID);
		public static final org.jooq.UniqueKey<edu.iup.chem.inventory.db.inventory.tables.records.RoleRecord>				KEY_ROLE_NAME						= createUniqueKey(
																																										edu.iup.chem.inventory.db.inventory.tables.Role.ROLE,
																																										edu.iup.chem.inventory.db.inventory.tables.Role.ROLE.NAME);
		public static final org.jooq.UniqueKey<edu.iup.chem.inventory.db.inventory.tables.records.RoomRecord>				KEY_ROOM_PRIMARY					= createUniqueKey(
																																										edu.iup.chem.inventory.db.inventory.tables.Room.ROOM,
																																										edu.iup.chem.inventory.db.inventory.tables.Room.ROOM.ROOM_);
		public static final org.jooq.UniqueKey<edu.iup.chem.inventory.db.inventory.tables.records.StructuresRecord>			KEY_STRUCTURES_PRIMARY				= createUniqueKey(
																																										edu.iup.chem.inventory.db.inventory.tables.Structures.STRUCTURES,
																																										edu.iup.chem.inventory.db.inventory.tables.Structures.STRUCTURES.CD_ID);
		public static final org.jooq.UniqueKey<edu.iup.chem.inventory.db.inventory.tables.records.StructuresUlRecord>		KEY_STRUCTURES_UL_PRIMARY			= createUniqueKey(
																																										edu.iup.chem.inventory.db.inventory.tables.StructuresUl.STRUCTURES_UL,
																																										edu.iup.chem.inventory.db.inventory.tables.StructuresUl.STRUCTURES_UL.UPDATE_ID);
		public static final org.jooq.UniqueKey<edu.iup.chem.inventory.db.inventory.tables.records.SynonymRecord>			KEY_SYNONYM_PRIMARY					= createUniqueKey(
																																										edu.iup.chem.inventory.db.inventory.tables.Synonym.SYNONYM,
																																										edu.iup.chem.inventory.db.inventory.tables.Synonym.SYNONYM.CAS);
		public static final org.jooq.UniqueKey<edu.iup.chem.inventory.db.inventory.tables.records.UserRecord>				KEY_USER_PRIMARY					= createUniqueKey(
																																										edu.iup.chem.inventory.db.inventory.tables.User.USER,
																																										edu.iup.chem.inventory.db.inventory.tables.User.USER.UID);
		public static final org.jooq.UniqueKey<edu.iup.chem.inventory.db.inventory.tables.records.UsersRecord>				KEY_USERS_PRIMARY					= createUniqueKey(
																																										edu.iup.chem.inventory.db.inventory.tables.Users.USERS,
																																										edu.iup.chem.inventory.db.inventory.tables.Users.USERS.UID);
		public static final org.jooq.UniqueKey<edu.iup.chem.inventory.db.inventory.tables.records.UsersRecord>				KEY_USERS_NAME						= createUniqueKey(
																																										edu.iup.chem.inventory.db.inventory.tables.Users.USERS,
																																										edu.iup.chem.inventory.db.inventory.tables.Users.USERS.NAME);
	}

	// IDENTITY definitions
	public static final org.jooq.Identity<edu.iup.chem.inventory.db.inventory.tables.records.AccessRecord, java.lang.Integer>																IDENTITY_ACCESS						= Identities0.IDENTITY_ACCESS;
	public static final org.jooq.Identity<edu.iup.chem.inventory.db.inventory.tables.records.LocationRecord, java.lang.Integer>																IDENTITY_LOCATION					= Identities0.IDENTITY_LOCATION;
	public static final org.jooq.Identity<edu.iup.chem.inventory.db.inventory.tables.records.RoleRecord, org.jooq.tools.unsigned.UInteger>													IDENTITY_ROLE						= Identities0.IDENTITY_ROLE;

	public static final org.jooq.Identity<edu.iup.chem.inventory.db.inventory.tables.records.StructuresRecord, java.lang.Integer>															IDENTITY_STRUCTURES					= Identities0.IDENTITY_STRUCTURES;
	public static final org.jooq.Identity<edu.iup.chem.inventory.db.inventory.tables.records.StructuresUlRecord, java.lang.Integer>															IDENTITY_STRUCTURES_UL				= Identities0.IDENTITY_STRUCTURES_UL;
	public static final org.jooq.Identity<edu.iup.chem.inventory.db.inventory.tables.records.UserRecord, java.lang.Integer>																	IDENTITY_USER						= Identities0.IDENTITY_USER;
	public static final org.jooq.Identity<edu.iup.chem.inventory.db.inventory.tables.records.ChemicalRecord, java.lang.Integer>																IDENTITY_CHEMICAL					= Identities0.IDENTITY_CHEMICAL;

	// UNIQUE and PRIMARY KEY definitions
	public static final org.jooq.UniqueKey<edu.iup.chem.inventory.db.inventory.tables.records.AccessRecord>																					KEY_ACCESS_PRIMARY					= UniqueKeys0.KEY_ACCESS_PRIMARY;
	public static final org.jooq.UniqueKey<edu.iup.chem.inventory.db.inventory.tables.records.ChemicalRecord>																				KEY_CHEMICAL_PRIMARY				= UniqueKeys0.KEY_CHEMICAL_PRIMARY;
	public static final org.jooq.UniqueKey<edu.iup.chem.inventory.db.inventory.tables.records.FieldDataFieldNameRecord>																		KEY_FIELD_DATA_FIELD_NAME_PRIMARY	= UniqueKeys0.KEY_FIELD_DATA_FIELD_NAME_PRIMARY;
	public static final org.jooq.UniqueKey<edu.iup.chem.inventory.db.inventory.tables.records.FieldDataFieldRoomRecord>																		KEY_FIELD_DATA_FIELD_ROOM_PRIMARY	= UniqueKeys0.KEY_FIELD_DATA_FIELD_ROOM_PRIMARY;
	public static final org.jooq.UniqueKey<edu.iup.chem.inventory.db.inventory.tables.records.JchempropertiesRecord>																		KEY_JCHEMPROPERTIES_PRIMARY			= UniqueKeys0.KEY_JCHEMPROPERTIES_PRIMARY;
	public static final org.jooq.UniqueKey<edu.iup.chem.inventory.db.inventory.tables.records.JchempropertiesCrRecord>																		KEY_JCHEMPROPERTIES_CR_PRIMARY		= UniqueKeys0.KEY_JCHEMPROPERTIES_CR_PRIMARY;
	public static final org.jooq.UniqueKey<edu.iup.chem.inventory.db.inventory.tables.records.LocationRecord>																				KEY_LOCATION_PRIMARY				= UniqueKeys0.KEY_LOCATION_PRIMARY;
	public static final org.jooq.UniqueKey<edu.iup.chem.inventory.db.inventory.tables.records.RoleRecord>																					KEY_ROLE_PRIMARY					= UniqueKeys0.KEY_ROLE_PRIMARY;
	public static final org.jooq.UniqueKey<edu.iup.chem.inventory.db.inventory.tables.records.RoleRecord>																					KEY_ROLE_NAME						= UniqueKeys0.KEY_ROLE_NAME;
	public static final org.jooq.UniqueKey<edu.iup.chem.inventory.db.inventory.tables.records.RoomRecord>																					KEY_ROOM_PRIMARY					= UniqueKeys0.KEY_ROOM_PRIMARY;
	public static final org.jooq.UniqueKey<edu.iup.chem.inventory.db.inventory.tables.records.StructuresRecord>																				KEY_STRUCTURES_PRIMARY				= UniqueKeys0.KEY_STRUCTURES_PRIMARY;
	public static final org.jooq.UniqueKey<edu.iup.chem.inventory.db.inventory.tables.records.StructuresUlRecord>																			KEY_STRUCTURES_UL_PRIMARY			= UniqueKeys0.KEY_STRUCTURES_UL_PRIMARY;
	public static final org.jooq.UniqueKey<edu.iup.chem.inventory.db.inventory.tables.records.SynonymRecord>																				KEY_SYNONYM_PRIMARY					= UniqueKeys0.KEY_SYNONYM_PRIMARY;

	public static final org.jooq.UniqueKey<edu.iup.chem.inventory.db.inventory.tables.records.UserRecord>																					KEY_USER_PRIMARY					= UniqueKeys0.KEY_USER_PRIMARY;
	public static final org.jooq.UniqueKey<edu.iup.chem.inventory.db.inventory.tables.records.UsersRecord>																					KEY_USERS_PRIMARY					= UniqueKeys0.KEY_USERS_PRIMARY;
	public static final org.jooq.UniqueKey<edu.iup.chem.inventory.db.inventory.tables.records.UsersRecord>																					KEY_USERS_NAME						= UniqueKeys0.KEY_USERS_NAME;
	// FOREIGN KEY definitions
	public static final org.jooq.ForeignKey<edu.iup.chem.inventory.db.inventory.tables.records.FieldDataFieldNameRecord, edu.iup.chem.inventory.db.inventory.tables.records.UsersRecord>	FIELD_DATA_FIELD_NAME_IBFK_1		= ForeignKeys0.FIELD_DATA_FIELD_NAME_IBFK_1;
	public static final org.jooq.ForeignKey<edu.iup.chem.inventory.db.inventory.tables.records.FieldDataFieldRoomRecord, edu.iup.chem.inventory.db.inventory.tables.records.UsersRecord>	FIELD_DATA_FIELD_ROOM_IBFK_1		= ForeignKeys0.FIELD_DATA_FIELD_ROOM_IBFK_1;

	public static final org.jooq.ForeignKey<edu.iup.chem.inventory.db.inventory.tables.records.UserRecord, edu.iup.chem.inventory.db.inventory.tables.records.RoleRecord>					USER_IBFK_2							= ForeignKeys0.USER_IBFK_2;

	public static final org.jooq.ForeignKey<edu.iup.chem.inventory.db.inventory.tables.records.UserRecord, edu.iup.chem.inventory.db.inventory.tables.records.RoleRecord>					USER_IBFK_3							= ForeignKeys0.USER_IBFK_3;

	public static final org.jooq.ForeignKey<edu.iup.chem.inventory.db.inventory.tables.records.UserRecord, edu.iup.chem.inventory.db.inventory.tables.records.RoomRecord>					USER_IBFK_1							= ForeignKeys0.USER_IBFK_1;

	/**
	 * No instances
	 */
	private Keys() {
	}
}
