/**
 * This class is generated by jOOQ
 */
package edu.iup.chem.inventory.db.inventory;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in inventory
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.1"},
                            comments = "This class is generated by jOOQ")
public final class Tables {

	/**
	 * The table inventory.access
	 */
	public static final edu.iup.chem.inventory.db.inventory.tables.Access ACCESS = edu.iup.chem.inventory.db.inventory.tables.Access.ACCESS;

	/**
	 * The table inventory.cancer
	 */
	public static final edu.iup.chem.inventory.db.inventory.tables.Cancer CANCER = edu.iup.chem.inventory.db.inventory.tables.Cancer.CANCER;

	/**
	 * The table inventory.chemical
	 */
	public static final edu.iup.chem.inventory.db.inventory.tables.Chemical CHEMICAL = edu.iup.chem.inventory.db.inventory.tables.Chemical.CHEMICAL;

	/**
	 * Data storage for field 5 (field_name)
	 */
	public static final edu.iup.chem.inventory.db.inventory.tables.FieldDataFieldName FIELD_DATA_FIELD_NAME = edu.iup.chem.inventory.db.inventory.tables.FieldDataFieldName.FIELD_DATA_FIELD_NAME;

	/**
	 * Data storage for field 7 (field_room)
	 */
	public static final edu.iup.chem.inventory.db.inventory.tables.FieldDataFieldRoom FIELD_DATA_FIELD_ROOM = edu.iup.chem.inventory.db.inventory.tables.FieldDataFieldRoom.FIELD_DATA_FIELD_ROOM;

	/**
	 * The table inventory.jchemproperties
	 */
	public static final edu.iup.chem.inventory.db.inventory.tables.Jchemproperties JCHEMPROPERTIES = edu.iup.chem.inventory.db.inventory.tables.Jchemproperties.JCHEMPROPERTIES;

	/**
	 * The table inventory.jchemproperties_cr
	 */
	public static final edu.iup.chem.inventory.db.inventory.tables.JchempropertiesCr JCHEMPROPERTIES_CR = edu.iup.chem.inventory.db.inventory.tables.JchempropertiesCr.JCHEMPROPERTIES_CR;

	/**
	 * The table inventory.location
	 */
	public static final edu.iup.chem.inventory.db.inventory.tables.Location LOCATION = edu.iup.chem.inventory.db.inventory.tables.Location.LOCATION;

	/**
	 * Stores user roles.
	 */
	public static final edu.iup.chem.inventory.db.inventory.tables.Role ROLE = edu.iup.chem.inventory.db.inventory.tables.Role.ROLE;

	/**
	 * The table inventory.room
	 */
	public static final edu.iup.chem.inventory.db.inventory.tables.Room ROOM = edu.iup.chem.inventory.db.inventory.tables.Room.ROOM;

	/**
	 * The table inventory.structures
	 */
	public static final edu.iup.chem.inventory.db.inventory.tables.Structures STRUCTURES = edu.iup.chem.inventory.db.inventory.tables.Structures.STRUCTURES;

	/**
	 * The table inventory.structures_ul
	 */
	public static final edu.iup.chem.inventory.db.inventory.tables.StructuresUl STRUCTURES_UL = edu.iup.chem.inventory.db.inventory.tables.StructuresUl.STRUCTURES_UL;

	/**
	 * The table inventory.struct_temp
	 */
	public static final edu.iup.chem.inventory.db.inventory.tables.StructTemp STRUCT_TEMP = edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP;

	/**
	 * The table inventory.synonym
	 */
	public static final edu.iup.chem.inventory.db.inventory.tables.Synonym SYNONYM = edu.iup.chem.inventory.db.inventory.tables.Synonym.SYNONYM;

	/**
	 * The table inventory.user
	 */
	public static final edu.iup.chem.inventory.db.inventory.tables.User USER = edu.iup.chem.inventory.db.inventory.tables.User.USER;

	/**
	 * Stores user data.
	 */
	public static final edu.iup.chem.inventory.db.inventory.tables.Users USERS = edu.iup.chem.inventory.db.inventory.tables.Users.USERS;

	/**
	 * No instances
	 */
	private Tables() {}
}
