/**
 * This class is generated by jOOQ
 */
package edu.iup.chem.inventory.db.inventory.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.1"},
                            comments = "This class is generated by jOOQ")
public class AccessRecord extends org.jooq.impl.UpdatableRecordImpl<edu.iup.chem.inventory.db.inventory.tables.records.AccessRecord> {

	private static final long serialVersionUID = -525981153;

	/**
	 * The table column <code>inventory.access.rid</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public void setRid(java.lang.Integer value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.Access.ACCESS.RID, value);
	}

	/**
	 * The table column <code>inventory.access.rid</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public java.lang.Integer getRid() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.Access.ACCESS.RID);
	}

	/**
	 * The table column <code>inventory.access.uid</code>
	 */
	public void setUid(java.lang.Integer value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.Access.ACCESS.UID, value);
	}

	/**
	 * The table column <code>inventory.access.uid</code>
	 */
	public java.lang.Integer getUid() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.Access.ACCESS.UID);
	}

	/**
	 * The table column <code>inventory.access.name</code>
	 */
	public void setName(java.lang.String value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.Access.ACCESS.NAME, value);
	}

	/**
	 * The table column <code>inventory.access.name</code>
	 */
	public java.lang.String getName() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.Access.ACCESS.NAME);
	}

	/**
	 * The table column <code>inventory.access.room</code>
	 */
	public void setRoom(java.lang.String value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.Access.ACCESS.ROOM, value);
	}

	/**
	 * The table column <code>inventory.access.room</code>
	 */
	public java.lang.String getRoom() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.Access.ACCESS.ROOM);
	}

	/**
	 * Create a detached AccessRecord
	 */
	public AccessRecord() {
		super(edu.iup.chem.inventory.db.inventory.tables.Access.ACCESS);
	}
}
