/**
 * This class is generated by jOOQ
 */
package edu.iup.chem.inventory.db.inventory.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.1"},
                            comments = "This class is generated by jOOQ")
public class CancerRecord extends org.jooq.impl.TableRecordImpl<edu.iup.chem.inventory.db.inventory.tables.records.CancerRecord> {

	private static final long serialVersionUID = -693557397;

	/**
	 * The table column <code>inventory.cancer.name</code>
	 */
	public void setName(java.lang.String value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.Cancer.CANCER.NAME, value);
	}

	/**
	 * The table column <code>inventory.cancer.name</code>
	 */
	public java.lang.String getName() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.Cancer.CANCER.NAME);
	}

	/**
	 * The table column <code>inventory.cancer.type</code>
	 */
	public void setType(java.lang.String value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.Cancer.CANCER.TYPE, value);
	}

	/**
	 * The table column <code>inventory.cancer.type</code>
	 */
	public java.lang.String getType() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.Cancer.CANCER.TYPE);
	}

	/**
	 * The table column <code>inventory.cancer.listing</code>
	 */
	public void setListing(java.lang.String value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.Cancer.CANCER.LISTING, value);
	}

	/**
	 * The table column <code>inventory.cancer.listing</code>
	 */
	public java.lang.String getListing() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.Cancer.CANCER.LISTING);
	}

	/**
	 * The table column <code>inventory.cancer.cas</code>
	 */
	public void setCas(java.lang.String value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.Cancer.CANCER.CAS, value);
	}

	/**
	 * The table column <code>inventory.cancer.cas</code>
	 */
	public java.lang.String getCas() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.Cancer.CANCER.CAS);
	}

	/**
	 * The table column <code>inventory.cancer.date</code>
	 */
	public void setDate(java.lang.String value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.Cancer.CANCER.DATE, value);
	}

	/**
	 * The table column <code>inventory.cancer.date</code>
	 */
	public java.lang.String getDate() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.Cancer.CANCER.DATE);
	}

	/**
	 * Create a detached CancerRecord
	 */
	public CancerRecord() {
		super(edu.iup.chem.inventory.db.inventory.tables.Cancer.CANCER);
	}
}
