/**
 * This class is generated by jOOQ
 */
package edu.iup.chem.inventory.db.inventory.tables.records;

/**
 * This class is generated by jOOQ.
 *
 * Data storage for field 5 (field_name)
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.1"},
                            comments = "This class is generated by jOOQ")
public class FieldDataFieldNameRecord extends org.jooq.impl.UpdatableRecordImpl<edu.iup.chem.inventory.db.inventory.tables.records.FieldDataFieldNameRecord> {

	private static final long serialVersionUID = 258192887;

	/**
	 * The entity type this data is attached to
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public void setEntityType(java.lang.String value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.FieldDataFieldName.FIELD_DATA_FIELD_NAME.ENTITY_TYPE, value);
	}

	/**
	 * The entity type this data is attached to
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public java.lang.String getEntityType() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.FieldDataFieldName.FIELD_DATA_FIELD_NAME.ENTITY_TYPE);
	}

	/**
	 * The field instance bundle to which this row belongs, used when deleting a field instance
	 */
	public void setBundle(java.lang.String value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.FieldDataFieldName.FIELD_DATA_FIELD_NAME.BUNDLE, value);
	}

	/**
	 * The field instance bundle to which this row belongs, used when deleting a field instance
	 */
	public java.lang.String getBundle() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.FieldDataFieldName.FIELD_DATA_FIELD_NAME.BUNDLE);
	}

	/**
	 * A boolean indicating whether this data item has been deleted
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public void setDeleted(java.lang.Byte value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.FieldDataFieldName.FIELD_DATA_FIELD_NAME.DELETED, value);
	}

	/**
	 * A boolean indicating whether this data item has been deleted
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public java.lang.Byte getDeleted() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.FieldDataFieldName.FIELD_DATA_FIELD_NAME.DELETED);
	}

	/**
	 * The entity id this data is attached to
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT field_data_field_name_ibfk_1
	 * FOREIGN KEY (entity_id)
	 * REFERENCES inventory.users (uid)
	 * </pre></code>
	 */
	public void setEntityId(org.jooq.tools.unsigned.UInteger value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.FieldDataFieldName.FIELD_DATA_FIELD_NAME.ENTITY_ID, value);
	}

	/**
	 * The entity id this data is attached to
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT field_data_field_name_ibfk_1
	 * FOREIGN KEY (entity_id)
	 * REFERENCES inventory.users (uid)
	 * </pre></code>
	 */
	public org.jooq.tools.unsigned.UInteger getEntityId() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.FieldDataFieldName.FIELD_DATA_FIELD_NAME.ENTITY_ID);
	}

	/**
	 * Link this record to a given {@link edu.iup.chem.inventory.db.inventory.tables.records.UsersRecord 
	 * UsersRecord}
	 */
	public void setEntityId(edu.iup.chem.inventory.db.inventory.tables.records.UsersRecord value) {
		if (value == null) {
			setValue(edu.iup.chem.inventory.db.inventory.tables.FieldDataFieldName.FIELD_DATA_FIELD_NAME.ENTITY_ID, null);
		}
		else {
			setValue(edu.iup.chem.inventory.db.inventory.tables.FieldDataFieldName.FIELD_DATA_FIELD_NAME.ENTITY_ID, value.getValue(edu.iup.chem.inventory.db.inventory.tables.Users.USERS.UID));
		}
	}

	/**
	 * The entity id this data is attached to
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT field_data_field_name_ibfk_1
	 * FOREIGN KEY (entity_id)
	 * REFERENCES inventory.users (uid)
	 * </pre></code>
	 */
	public edu.iup.chem.inventory.db.inventory.tables.records.UsersRecord fetchUsers() {
		return create()
			.selectFrom(edu.iup.chem.inventory.db.inventory.tables.Users.USERS)
			.where(edu.iup.chem.inventory.db.inventory.tables.Users.USERS.UID.equal(getValue(edu.iup.chem.inventory.db.inventory.tables.FieldDataFieldName.FIELD_DATA_FIELD_NAME.ENTITY_ID)))
			.fetchOne();
	}

	/**
	 * The entity revision id this data is attached to, or NULL if the entity type is not versioned
	 */
	public void setRevisionId(org.jooq.tools.unsigned.UInteger value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.FieldDataFieldName.FIELD_DATA_FIELD_NAME.REVISION_ID, value);
	}

	/**
	 * The entity revision id this data is attached to, or NULL if the entity type is not versioned
	 */
	public org.jooq.tools.unsigned.UInteger getRevisionId() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.FieldDataFieldName.FIELD_DATA_FIELD_NAME.REVISION_ID);
	}

	/**
	 * The language for this data item.
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public void setLanguage(java.lang.String value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.FieldDataFieldName.FIELD_DATA_FIELD_NAME.LANGUAGE, value);
	}

	/**
	 * The language for this data item.
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public java.lang.String getLanguage() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.FieldDataFieldName.FIELD_DATA_FIELD_NAME.LANGUAGE);
	}

	/**
	 * The sequence number for this data item, used for multi-value fields
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public void setDelta(org.jooq.tools.unsigned.UInteger value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.FieldDataFieldName.FIELD_DATA_FIELD_NAME.DELTA, value);
	}

	/**
	 * The sequence number for this data item, used for multi-value fields
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public org.jooq.tools.unsigned.UInteger getDelta() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.FieldDataFieldName.FIELD_DATA_FIELD_NAME.DELTA);
	}

	/**
	 * The table column <code>inventory.field_data_field_name.field_name_value</code>
	 */
	public void setFieldNameValue(java.lang.String value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.FieldDataFieldName.FIELD_DATA_FIELD_NAME.FIELD_NAME_VALUE, value);
	}

	/**
	 * The table column <code>inventory.field_data_field_name.field_name_value</code>
	 */
	public java.lang.String getFieldNameValue() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.FieldDataFieldName.FIELD_DATA_FIELD_NAME.FIELD_NAME_VALUE);
	}

	/**
	 * The table column <code>inventory.field_data_field_name.field_name_format</code>
	 */
	public void setFieldNameFormat(java.lang.String value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.FieldDataFieldName.FIELD_DATA_FIELD_NAME.FIELD_NAME_FORMAT, value);
	}

	/**
	 * The table column <code>inventory.field_data_field_name.field_name_format</code>
	 */
	public java.lang.String getFieldNameFormat() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.FieldDataFieldName.FIELD_DATA_FIELD_NAME.FIELD_NAME_FORMAT);
	}

	/**
	 * Create a detached FieldDataFieldNameRecord
	 */
	public FieldDataFieldNameRecord() {
		super(edu.iup.chem.inventory.db.inventory.tables.FieldDataFieldName.FIELD_DATA_FIELD_NAME);
	}
}
