/**
 * This class is generated by jOOQ
 */
package edu.iup.chem.inventory.db.inventory.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.1"},
                            comments = "This class is generated by jOOQ")
public class JchempropertiesCrRecord extends org.jooq.impl.UpdatableRecordImpl<edu.iup.chem.inventory.db.inventory.tables.records.JchempropertiesCrRecord> {

	private static final long serialVersionUID = -849179342;

	/**
	 * The table column <code>inventory.jchemproperties_cr.cache_id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public void setCacheId(java.lang.String value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.JchempropertiesCr.JCHEMPROPERTIES_CR.CACHE_ID, value);
	}

	/**
	 * The table column <code>inventory.jchemproperties_cr.cache_id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public java.lang.String getCacheId() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.JchempropertiesCr.JCHEMPROPERTIES_CR.CACHE_ID);
	}

	/**
	 * The table column <code>inventory.jchemproperties_cr.registration_time</code>
	 */
	public void setRegistrationTime(java.lang.String value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.JchempropertiesCr.JCHEMPROPERTIES_CR.REGISTRATION_TIME, value);
	}

	/**
	 * The table column <code>inventory.jchemproperties_cr.registration_time</code>
	 */
	public java.lang.String getRegistrationTime() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.JchempropertiesCr.JCHEMPROPERTIES_CR.REGISTRATION_TIME);
	}

	/**
	 * The table column <code>inventory.jchemproperties_cr.is_protected</code>
	 */
	public void setIsProtected(java.lang.Byte value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.JchempropertiesCr.JCHEMPROPERTIES_CR.IS_PROTECTED, value);
	}

	/**
	 * The table column <code>inventory.jchemproperties_cr.is_protected</code>
	 */
	public java.lang.Byte getIsProtected() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.JchempropertiesCr.JCHEMPROPERTIES_CR.IS_PROTECTED);
	}

	/**
	 * Create a detached JchempropertiesCrRecord
	 */
	public JchempropertiesCrRecord() {
		super(edu.iup.chem.inventory.db.inventory.tables.JchempropertiesCr.JCHEMPROPERTIES_CR);
	}
}
