/**
 * This class is generated by jOOQ
 */
package edu.iup.chem.inventory.db.inventory.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.1"},
                            comments = "This class is generated by jOOQ")
public class JchempropertiesRecord extends org.jooq.impl.UpdatableRecordImpl<edu.iup.chem.inventory.db.inventory.tables.records.JchempropertiesRecord> {

	private static final long serialVersionUID = -1152158599;

	/**
	 * The table column <code>inventory.jchemproperties.prop_name</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public void setPropName(java.lang.String value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.Jchemproperties.JCHEMPROPERTIES.PROP_NAME, value);
	}

	/**
	 * The table column <code>inventory.jchemproperties.prop_name</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public java.lang.String getPropName() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.Jchemproperties.JCHEMPROPERTIES.PROP_NAME);
	}

	/**
	 * The table column <code>inventory.jchemproperties.prop_value</code>
	 */
	public void setPropValue(java.lang.String value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.Jchemproperties.JCHEMPROPERTIES.PROP_VALUE, value);
	}

	/**
	 * The table column <code>inventory.jchemproperties.prop_value</code>
	 */
	public java.lang.String getPropValue() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.Jchemproperties.JCHEMPROPERTIES.PROP_VALUE);
	}

	/**
	 * The table column <code>inventory.jchemproperties.prop_value_ext</code>
	 */
	public void setPropValueExt(byte[] value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.Jchemproperties.JCHEMPROPERTIES.PROP_VALUE_EXT, value);
	}

	/**
	 * The table column <code>inventory.jchemproperties.prop_value_ext</code>
	 */
	public byte[] getPropValueExt() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.Jchemproperties.JCHEMPROPERTIES.PROP_VALUE_EXT);
	}

	/**
	 * Create a detached JchempropertiesRecord
	 */
	public JchempropertiesRecord() {
		super(edu.iup.chem.inventory.db.inventory.tables.Jchemproperties.JCHEMPROPERTIES);
	}
}
