/**
 * This class is generated by jOOQ
 */
package edu.iup.chem.inventory.db.inventory.tables.records;

import edu.iup.chem.inventory.Utils;
import edu.iup.chem.inventory.amount.ChemicalAmount;
import edu.iup.chem.inventory.amount.ChemicalAmountFactory;
import edu.iup.chem.inventory.amount.InventoryAmount;
import edu.iup.chem.inventory.amount.InventoryAmountFactory;
import edu.iup.chem.inventory.dao.ChemicalDao;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value = { "http://www.jooq.org", "2.5.1" }, comments = "This class is generated by jOOQ")
public class LocationRecord
		extends
		org.jooq.impl.UpdatableRecordImpl<edu.iup.chem.inventory.db.inventory.tables.records.LocationRecord> {

	private static final long	serialVersionUID	= -1191398649;
	private ChemicalAmount		amount				= null;
	private InventoryAmount		invAmount			= null;

	private ChemicalRecord		chemical			= null;

	/**
	 * Create a detached LocationRecord
	 */
	public LocationRecord() {
		super(edu.iup.chem.inventory.db.inventory.tables.Location.LOCATION);
	}

	/**
	 * The table column <code>inventory.location.active</code>
	 */
	public java.lang.Byte getActive() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.Location.LOCATION.ACTIVE);
	}

	/**
	 * The table column <code>inventory.location.amount</code>
	 */
	public java.lang.Double getAmount() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.Location.LOCATION.AMOUNT);
	}

	/**
	 * The table column <code>inventory.location.arrival</code>
	 */
	public java.sql.Date getArrival() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.Location.LOCATION.ARRIVAL);
	}

	public String getBottle() {
		return (getType() == null || getType().equals("null") ? "" : getType())
				+ getBottleNo();
	}

	/**
	 * The table column <code>inventory.location.bottle_no</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public java.lang.Integer getBottleNo() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.Location.LOCATION.BOTTLE_NO);
	}

	/**
	 * The table column <code>inventory.location.cas</code>
	 */
	public java.lang.String getCas() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.Location.LOCATION.CAS);
	}

	public ChemicalAmount getChemicalAmount() {
		// Check if the amount has not been set, or if it has been changed since
		// we last set it
		if (amount == null || amount.getQuantity() != getAmount()
				|| !amount.getUnit().equals(getUnits())) {
			amount = ChemicalAmountFactory.getChemicalAmount(getAmount(),
					getUnits());
		}

		return amount;
	}

	public ChemicalRecord getChemicalRecord() {
		if (chemical == null) {
			chemical = ChemicalDao.getById(getCid());
		}

		return chemical;
	}

	public Integer getCid() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.Location.LOCATION.CID);
	}

	public String getDescription() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.Location.LOCATION.DESCRIPTION);
	}

	/**
	 * The table column <code>inventory.location.expiration</code>
	 */
	public java.sql.Date getExpiration() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.Location.LOCATION.EXPIRATION);
	}

	/**
	 * The table column <code>inventory.location.instructor</code>
	 */
	public java.lang.String getInstructor() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.Location.LOCATION.INSTRUCTOR);
	}

	public InventoryAmount getInventoryAmount() {
		if (invAmount == null) {
			invAmount = InventoryAmountFactory.getAmount(getChemicalAmount(),
					getChemicalRecord().getDensityWithUnits());
		}

		return invAmount;
	}

	public String getName() {
		return getChemicalRecord().getName();
	}

	/**
	 * The table column <code>inventory.location.part_no</code>
	 */
	public java.lang.Integer getPartNo() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.Location.LOCATION.PART_NO);
	}

	/**
	 * The table column <code>inventory.location.room</code>
	 */
	public java.lang.String getRoom() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.Location.LOCATION.ROOM);
	}

	/**
	 * The table column <code>inventory.location.shelf</code>
	 */
	public java.lang.String getShelf() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.Location.LOCATION.SHELF);
	}

	/**
	 * The table column <code>inventory.location.supplier</code>
	 */
	public java.lang.String getSupplier() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.Location.LOCATION.SUPPLIER);
	}

	public java.lang.String getType() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.Location.LOCATION.TYPE);
	}

	/**
	 * The table column <code>inventory.location.units</code>
	 */
	public java.lang.String getUnits() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.Location.LOCATION.UNITS);
	}

	/**
	 * The table column <code>inventory.location.active</code>
	 */
	public void setActive(final java.lang.Byte value) {
		setValue(
				edu.iup.chem.inventory.db.inventory.tables.Location.LOCATION.ACTIVE,
				value);
	}

	/**
	 * The table column <code>inventory.location.amount</code>
	 */
	public void setAmount(final java.lang.Double value) {
		setValue(
				edu.iup.chem.inventory.db.inventory.tables.Location.LOCATION.AMOUNT,
				value);
	}

	/**
	 * The table column <code>inventory.location.arrival</code>
	 */
	public void setArrival(final java.sql.Date value) {
		setValue(
				edu.iup.chem.inventory.db.inventory.tables.Location.LOCATION.ARRIVAL,
				value);
	}

	public void setBottle(final String value) {
		final String[] values = Utils.splitBottle(value);
		setType(values[0]);
		setBottleNo(Integer.parseInt(values[1]));
	}

	/**
	 * The table column <code>inventory.location.bottle_no</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public void setBottleNo(final java.lang.Integer value) {
		setValue(
				edu.iup.chem.inventory.db.inventory.tables.Location.LOCATION.BOTTLE_NO,
				value);
	}

	/**
	 * The table column <code>inventory.location.cas</code>
	 */
	public void setCas(final java.lang.String value) {
		setValue(
				edu.iup.chem.inventory.db.inventory.tables.Location.LOCATION.CAS,
				value);
	}

	public void setChemicalAmount(final ChemicalAmount am) {
		amount = am;
		setAmount(am.getQuantity());
		setUnits(am.getUnit());
	}

	public void setCid(final Integer value) {
		setValue(
				edu.iup.chem.inventory.db.inventory.tables.Location.LOCATION.CID,
				value);
	}

	public void setDescription(final String value) {
		setValue(
				edu.iup.chem.inventory.db.inventory.tables.Location.LOCATION.DESCRIPTION,
				value);
	}

	/**
	 * The table column <code>inventory.location.expiration</code>
	 */
	public void setExpiration(final java.sql.Date value) {
		setValue(
				edu.iup.chem.inventory.db.inventory.tables.Location.LOCATION.EXPIRATION,
				value);
	}

	/**
	 * The table column <code>inventory.location.instructor</code>
	 */
	public void setInstructor(final java.lang.String value) {
		setValue(
				edu.iup.chem.inventory.db.inventory.tables.Location.LOCATION.INSTRUCTOR,
				value);
	}

	public void setInventoryAmount(final ChemicalAmount am) {
		setChemicalAmount(am);
		invAmount = InventoryAmountFactory.getAmount(am, getChemicalRecord()
				.getDensityWithUnits());
	}

	/**
	 * The table column <code>inventory.location.part_no</code>
	 */
	public void setPartNo(final java.lang.Integer value) {
		setValue(
				edu.iup.chem.inventory.db.inventory.tables.Location.LOCATION.PART_NO,
				value);
	}

	/**
	 * The table column <code>inventory.location.room</code>
	 */
	public void setRoom(final java.lang.String value) {
		setValue(
				edu.iup.chem.inventory.db.inventory.tables.Location.LOCATION.ROOM,
				value);
	}

	/**
	 * The table column <code>inventory.location.shelf</code>
	 */
	public void setShelf(final java.lang.String value) {
		setValue(
				edu.iup.chem.inventory.db.inventory.tables.Location.LOCATION.SHELF,
				value);
	}

	/**
	 * The table column <code>inventory.location.supplier</code>
	 */
	public void setSupplier(final java.lang.String value) {
		setValue(
				edu.iup.chem.inventory.db.inventory.tables.Location.LOCATION.SUPPLIER,
				value);
	}

	public void setType(final String value) {
		setValue(
				edu.iup.chem.inventory.db.inventory.tables.Location.LOCATION.TYPE,
				value);
	}

	/**
	 * The table column <code>inventory.location.units</code>
	 */
	public void setUnits(final java.lang.String value) {
		setValue(
				edu.iup.chem.inventory.db.inventory.tables.Location.LOCATION.UNITS,
				value);
	}
}
