/**
 * This class is generated by jOOQ
 */
package edu.iup.chem.inventory.db.inventory.tables.records;

/**
 * This class is generated by jOOQ.
 * 
 * Stores user roles.
 */
@javax.annotation.Generated(value = { "http://www.jooq.org", "2.5.1" }, comments = "This class is generated by jOOQ")
public class RoleRecord
		extends
		org.jooq.impl.UpdatableRecordImpl<edu.iup.chem.inventory.db.inventory.tables.records.RoleRecord> {

	private static final long	serialVersionUID	= 2097097273;

	/**
	 * Create a detached RoleRecord
	 */
	public RoleRecord() {
		super(edu.iup.chem.inventory.db.inventory.tables.Role.ROLE);
	}

	/**
	 * Primary Key: Unique role ID.
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public java.util.List<edu.iup.chem.inventory.db.inventory.tables.records.UserRecord> fetchUserListByRid() {
		return create()
				.selectFrom(
						edu.iup.chem.inventory.db.inventory.tables.User.USER)
				.where(edu.iup.chem.inventory.db.inventory.tables.User.USER.RID
						.equal(getValue(edu.iup.chem.inventory.db.inventory.tables.Role.ROLE.RID)))
				.fetch();
	}

	/**
	 * Unique role name.
	 */
	public java.util.List<edu.iup.chem.inventory.db.inventory.tables.records.UserRecord> fetchUserListByRoleName() {
		return create()
				.selectFrom(
						edu.iup.chem.inventory.db.inventory.tables.User.USER)
				.where(edu.iup.chem.inventory.db.inventory.tables.User.USER.ROLE_NAME
						.equal(getValue(edu.iup.chem.inventory.db.inventory.tables.Role.ROLE.NAME)))
				.fetch();
	}

	/**
	 * Unique role name.
	 */
	public java.lang.String getName() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.Role.ROLE.NAME);
	}

	/**
	 * Primary Key: Unique role ID.
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public org.jooq.tools.unsigned.UInteger getRid() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.Role.ROLE.RID);
	}

	/**
	 * The weight of this role in listings and the user interface.
	 */
	public java.lang.Integer getWeight() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.Role.ROLE.WEIGHT);
	}

	/**
	 * Unique role name.
	 */
	public void setName(final java.lang.String value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.Role.ROLE.NAME,
				value);
	}

	/**
	 * Primary Key: Unique role ID.
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public void setRid(final org.jooq.tools.unsigned.UInteger value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.Role.ROLE.RID,
				value);
	}

	/**
	 * The weight of this role in listings and the user interface.
	 */
	public void setWeight(final java.lang.Integer value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.Role.ROLE.WEIGHT,
				value);
	}

	@Override
	public String toString() {
		return getName();
	}
}
