/**
 * This class is generated by jOOQ
 */
package edu.iup.chem.inventory.db.inventory.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value = { "http://www.jooq.org", "2.5.1" }, comments = "This class is generated by jOOQ")
public class RoomRecord
		extends
		org.jooq.impl.UpdatableRecordImpl<edu.iup.chem.inventory.db.inventory.tables.records.RoomRecord> {

	private static final long	serialVersionUID	= 1432933838;

	/**
	 * Create a detached RoomRecord
	 */
	public RoomRecord() {
		super(edu.iup.chem.inventory.db.inventory.tables.Room.ROOM);
	}

	/**
	 * The table column <code>inventory.room.room</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public java.util.List<edu.iup.chem.inventory.db.inventory.tables.records.UserRecord> fetchUserList() {
		return create()
				.selectFrom(
						edu.iup.chem.inventory.db.inventory.tables.User.USER)
				.where(edu.iup.chem.inventory.db.inventory.tables.User.USER.ROOM
						.equal(getValue(edu.iup.chem.inventory.db.inventory.tables.Room.ROOM.ROOM_)))
				.fetch();
	}

	/**
	 * The table column <code>inventory.room.room</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public java.lang.String getRoom() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.Room.ROOM.ROOM_);
	}

	/**
	 * The table column <code>inventory.room.room</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public void setRoom(final java.lang.String value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.Room.ROOM.ROOM_,
				value);
	}

	@Override
	public String toString() {
		return getRoom();
	}
}
