/**
 * This class is generated by jOOQ
 */
package edu.iup.chem.inventory.db.inventory.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.1"},
                            comments = "This class is generated by jOOQ")
public class StructTempRecord extends org.jooq.impl.TableRecordImpl<edu.iup.chem.inventory.db.inventory.tables.records.StructTempRecord> {

	private static final long serialVersionUID = 468583594;

	/**
	 * The table column <code>inventory.struct_temp.cd_id</code>
	 */
	public void setCdId(java.lang.Integer value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP.CD_ID, value);
	}

	/**
	 * The table column <code>inventory.struct_temp.cd_id</code>
	 */
	public java.lang.Integer getCdId() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP.CD_ID);
	}

	/**
	 * The table column <code>inventory.struct_temp.cd_structure</code>
	 */
	public void setCdStructure(byte[] value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP.CD_STRUCTURE, value);
	}

	/**
	 * The table column <code>inventory.struct_temp.cd_structure</code>
	 */
	public byte[] getCdStructure() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP.CD_STRUCTURE);
	}

	/**
	 * The table column <code>inventory.struct_temp.cd_smiles</code>
	 */
	public void setCdSmiles(java.lang.String value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP.CD_SMILES, value);
	}

	/**
	 * The table column <code>inventory.struct_temp.cd_smiles</code>
	 */
	public java.lang.String getCdSmiles() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP.CD_SMILES);
	}

	/**
	 * The table column <code>inventory.struct_temp.cd_formula</code>
	 */
	public void setCdFormula(java.lang.String value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP.CD_FORMULA, value);
	}

	/**
	 * The table column <code>inventory.struct_temp.cd_formula</code>
	 */
	public java.lang.String getCdFormula() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP.CD_FORMULA);
	}

	/**
	 * The table column <code>inventory.struct_temp.cd_sortable_formula</code>
	 */
	public void setCdSortableFormula(java.lang.String value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP.CD_SORTABLE_FORMULA, value);
	}

	/**
	 * The table column <code>inventory.struct_temp.cd_sortable_formula</code>
	 */
	public java.lang.String getCdSortableFormula() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP.CD_SORTABLE_FORMULA);
	}

	/**
	 * The table column <code>inventory.struct_temp.cd_molweight</code>
	 */
	public void setCdMolweight(java.lang.Double value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP.CD_MOLWEIGHT, value);
	}

	/**
	 * The table column <code>inventory.struct_temp.cd_molweight</code>
	 */
	public java.lang.Double getCdMolweight() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP.CD_MOLWEIGHT);
	}

	/**
	 * The table column <code>inventory.struct_temp.cd_hash</code>
	 */
	public void setCdHash(java.lang.Integer value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP.CD_HASH, value);
	}

	/**
	 * The table column <code>inventory.struct_temp.cd_hash</code>
	 */
	public java.lang.Integer getCdHash() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP.CD_HASH);
	}

	/**
	 * The table column <code>inventory.struct_temp.cd_flags</code>
	 */
	public void setCdFlags(java.lang.String value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP.CD_FLAGS, value);
	}

	/**
	 * The table column <code>inventory.struct_temp.cd_flags</code>
	 */
	public java.lang.String getCdFlags() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP.CD_FLAGS);
	}

	/**
	 * The table column <code>inventory.struct_temp.cd_timestamp</code>
	 */
	public void setCdTimestamp(java.sql.Timestamp value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP.CD_TIMESTAMP, value);
	}

	/**
	 * The table column <code>inventory.struct_temp.cd_timestamp</code>
	 */
	public java.sql.Timestamp getCdTimestamp() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP.CD_TIMESTAMP);
	}

	/**
	 * The table column <code>inventory.struct_temp.cd_pre_calculated</code>
	 */
	public void setCdPreCalculated(java.lang.Byte value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP.CD_PRE_CALCULATED, value);
	}

	/**
	 * The table column <code>inventory.struct_temp.cd_pre_calculated</code>
	 */
	public java.lang.Byte getCdPreCalculated() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP.CD_PRE_CALCULATED);
	}

	/**
	 * The table column <code>inventory.struct_temp.cd_fp1</code>
	 */
	public void setCdFp1(java.lang.Integer value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP.CD_FP1, value);
	}

	/**
	 * The table column <code>inventory.struct_temp.cd_fp1</code>
	 */
	public java.lang.Integer getCdFp1() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP.CD_FP1);
	}

	/**
	 * The table column <code>inventory.struct_temp.cd_fp2</code>
	 */
	public void setCdFp2(java.lang.Integer value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP.CD_FP2, value);
	}

	/**
	 * The table column <code>inventory.struct_temp.cd_fp2</code>
	 */
	public java.lang.Integer getCdFp2() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP.CD_FP2);
	}

	/**
	 * The table column <code>inventory.struct_temp.cd_fp3</code>
	 */
	public void setCdFp3(java.lang.Integer value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP.CD_FP3, value);
	}

	/**
	 * The table column <code>inventory.struct_temp.cd_fp3</code>
	 */
	public java.lang.Integer getCdFp3() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP.CD_FP3);
	}

	/**
	 * The table column <code>inventory.struct_temp.cd_fp4</code>
	 */
	public void setCdFp4(java.lang.Integer value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP.CD_FP4, value);
	}

	/**
	 * The table column <code>inventory.struct_temp.cd_fp4</code>
	 */
	public java.lang.Integer getCdFp4() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP.CD_FP4);
	}

	/**
	 * The table column <code>inventory.struct_temp.cd_fp5</code>
	 */
	public void setCdFp5(java.lang.Integer value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP.CD_FP5, value);
	}

	/**
	 * The table column <code>inventory.struct_temp.cd_fp5</code>
	 */
	public java.lang.Integer getCdFp5() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP.CD_FP5);
	}

	/**
	 * The table column <code>inventory.struct_temp.cd_fp6</code>
	 */
	public void setCdFp6(java.lang.Integer value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP.CD_FP6, value);
	}

	/**
	 * The table column <code>inventory.struct_temp.cd_fp6</code>
	 */
	public java.lang.Integer getCdFp6() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP.CD_FP6);
	}

	/**
	 * The table column <code>inventory.struct_temp.cd_fp7</code>
	 */
	public void setCdFp7(java.lang.Integer value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP.CD_FP7, value);
	}

	/**
	 * The table column <code>inventory.struct_temp.cd_fp7</code>
	 */
	public java.lang.Integer getCdFp7() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP.CD_FP7);
	}

	/**
	 * The table column <code>inventory.struct_temp.cd_fp8</code>
	 */
	public void setCdFp8(java.lang.Integer value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP.CD_FP8, value);
	}

	/**
	 * The table column <code>inventory.struct_temp.cd_fp8</code>
	 */
	public java.lang.Integer getCdFp8() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP.CD_FP8);
	}

	/**
	 * The table column <code>inventory.struct_temp.cd_fp9</code>
	 */
	public void setCdFp9(java.lang.Integer value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP.CD_FP9, value);
	}

	/**
	 * The table column <code>inventory.struct_temp.cd_fp9</code>
	 */
	public java.lang.Integer getCdFp9() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP.CD_FP9);
	}

	/**
	 * The table column <code>inventory.struct_temp.cd_fp10</code>
	 */
	public void setCdFp10(java.lang.Integer value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP.CD_FP10, value);
	}

	/**
	 * The table column <code>inventory.struct_temp.cd_fp10</code>
	 */
	public java.lang.Integer getCdFp10() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP.CD_FP10);
	}

	/**
	 * The table column <code>inventory.struct_temp.cd_fp11</code>
	 */
	public void setCdFp11(java.lang.Integer value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP.CD_FP11, value);
	}

	/**
	 * The table column <code>inventory.struct_temp.cd_fp11</code>
	 */
	public java.lang.Integer getCdFp11() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP.CD_FP11);
	}

	/**
	 * The table column <code>inventory.struct_temp.cd_fp12</code>
	 */
	public void setCdFp12(java.lang.Integer value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP.CD_FP12, value);
	}

	/**
	 * The table column <code>inventory.struct_temp.cd_fp12</code>
	 */
	public java.lang.Integer getCdFp12() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP.CD_FP12);
	}

	/**
	 * The table column <code>inventory.struct_temp.cd_fp13</code>
	 */
	public void setCdFp13(java.lang.Integer value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP.CD_FP13, value);
	}

	/**
	 * The table column <code>inventory.struct_temp.cd_fp13</code>
	 */
	public java.lang.Integer getCdFp13() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP.CD_FP13);
	}

	/**
	 * The table column <code>inventory.struct_temp.cd_fp14</code>
	 */
	public void setCdFp14(java.lang.Integer value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP.CD_FP14, value);
	}

	/**
	 * The table column <code>inventory.struct_temp.cd_fp14</code>
	 */
	public java.lang.Integer getCdFp14() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP.CD_FP14);
	}

	/**
	 * The table column <code>inventory.struct_temp.cd_fp15</code>
	 */
	public void setCdFp15(java.lang.Integer value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP.CD_FP15, value);
	}

	/**
	 * The table column <code>inventory.struct_temp.cd_fp15</code>
	 */
	public java.lang.Integer getCdFp15() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP.CD_FP15);
	}

	/**
	 * The table column <code>inventory.struct_temp.cd_fp16</code>
	 */
	public void setCdFp16(java.lang.Integer value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP.CD_FP16, value);
	}

	/**
	 * The table column <code>inventory.struct_temp.cd_fp16</code>
	 */
	public java.lang.Integer getCdFp16() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP.CD_FP16);
	}

	/**
	 * Create a detached StructTempRecord
	 */
	public StructTempRecord() {
		super(edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP);
	}
}
