/**
 * This class is generated by jOOQ
 */
package edu.iup.chem.inventory.db.inventory.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.1"},
                            comments = "This class is generated by jOOQ")
public class StructuresUlRecord extends org.jooq.impl.UpdatableRecordImpl<edu.iup.chem.inventory.db.inventory.tables.records.StructuresUlRecord> {

	private static final long serialVersionUID = 1718087890;

	/**
	 * The table column <code>inventory.structures_ul.update_id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public void setUpdateId(java.lang.Integer value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.StructuresUl.STRUCTURES_UL.UPDATE_ID, value);
	}

	/**
	 * The table column <code>inventory.structures_ul.update_id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public java.lang.Integer getUpdateId() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.StructuresUl.STRUCTURES_UL.UPDATE_ID);
	}

	/**
	 * The table column <code>inventory.structures_ul.update_info</code>
	 */
	public void setUpdateInfo(java.lang.String value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.StructuresUl.STRUCTURES_UL.UPDATE_INFO, value);
	}

	/**
	 * The table column <code>inventory.structures_ul.update_info</code>
	 */
	public java.lang.String getUpdateInfo() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.StructuresUl.STRUCTURES_UL.UPDATE_INFO);
	}

	/**
	 * The table column <code>inventory.structures_ul.cache_id</code>
	 */
	public void setCacheId(java.lang.String value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.StructuresUl.STRUCTURES_UL.CACHE_ID, value);
	}

	/**
	 * The table column <code>inventory.structures_ul.cache_id</code>
	 */
	public java.lang.String getCacheId() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.StructuresUl.STRUCTURES_UL.CACHE_ID);
	}

	/**
	 * Create a detached StructuresUlRecord
	 */
	public StructuresUlRecord() {
		super(edu.iup.chem.inventory.db.inventory.tables.StructuresUl.STRUCTURES_UL);
	}
}
