/**
 * This class is generated by jOOQ
 */
package edu.iup.chem.inventory.db.inventory.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.1"},
                            comments = "This class is generated by jOOQ")
public class SynonymRecord extends org.jooq.impl.UpdatableRecordImpl<edu.iup.chem.inventory.db.inventory.tables.records.SynonymRecord> {

	private static final long serialVersionUID = -1882788471;

	/**
	 * The table column <code>inventory.synonym.cas</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public void setCas(java.lang.String value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.Synonym.SYNONYM.CAS, value);
	}

	/**
	 * The table column <code>inventory.synonym.cas</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public java.lang.String getCas() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.Synonym.SYNONYM.CAS);
	}

	/**
	 * The table column <code>inventory.synonym.names</code>
	 */
	public void setNames(java.lang.String value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.Synonym.SYNONYM.NAMES, value);
	}

	/**
	 * The table column <code>inventory.synonym.names</code>
	 */
	public java.lang.String getNames() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.Synonym.SYNONYM.NAMES);
	}

	/**
	 * Create a detached SynonymRecord
	 */
	public SynonymRecord() {
		super(edu.iup.chem.inventory.db.inventory.tables.Synonym.SYNONYM);
	}
}
