/**
 * This class is generated by jOOQ
 */
package edu.iup.chem.inventory.db.inventory.tables.records;

/**
 * This class is generated by jOOQ.
 *
 * Stores user data.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.1"},
                            comments = "This class is generated by jOOQ")
public class UsersRecord extends org.jooq.impl.UpdatableRecordImpl<edu.iup.chem.inventory.db.inventory.tables.records.UsersRecord> {

	private static final long serialVersionUID = 1121621806;

	/**
	 * Primary Key: Unique user ID.
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public void setUid(org.jooq.tools.unsigned.UInteger value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.Users.USERS.UID, value);
	}

	/**
	 * Primary Key: Unique user ID.
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public org.jooq.tools.unsigned.UInteger getUid() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.Users.USERS.UID);
	}

	/**
	 * Primary Key: Unique user ID.
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public java.util.List<edu.iup.chem.inventory.db.inventory.tables.records.FieldDataFieldNameRecord> fetchFieldDataFieldNameList() {
		return create()
			.selectFrom(edu.iup.chem.inventory.db.inventory.tables.FieldDataFieldName.FIELD_DATA_FIELD_NAME)
			.where(edu.iup.chem.inventory.db.inventory.tables.FieldDataFieldName.FIELD_DATA_FIELD_NAME.ENTITY_ID.equal(getValue(edu.iup.chem.inventory.db.inventory.tables.Users.USERS.UID)))
			.fetch();
	}

	/**
	 * Primary Key: Unique user ID.
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public java.util.List<edu.iup.chem.inventory.db.inventory.tables.records.FieldDataFieldRoomRecord> fetchFieldDataFieldRoomList() {
		return create()
			.selectFrom(edu.iup.chem.inventory.db.inventory.tables.FieldDataFieldRoom.FIELD_DATA_FIELD_ROOM)
			.where(edu.iup.chem.inventory.db.inventory.tables.FieldDataFieldRoom.FIELD_DATA_FIELD_ROOM.ENTITY_ID.equal(getValue(edu.iup.chem.inventory.db.inventory.tables.Users.USERS.UID)))
			.fetch();
	}

	/**
	 * Unique user name.
	 */
	public void setName(java.lang.String value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.Users.USERS.NAME, value);
	}

	/**
	 * Unique user name.
	 */
	public java.lang.String getName() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.Users.USERS.NAME);
	}

	/**
	 * User’s password (hashed).
	 */
	public void setPass(java.lang.String value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.Users.USERS.PASS, value);
	}

	/**
	 * User’s password (hashed).
	 */
	public java.lang.String getPass() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.Users.USERS.PASS);
	}

	/**
	 * User’s e-mail address.
	 */
	public void setMail(java.lang.String value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.Users.USERS.MAIL, value);
	}

	/**
	 * User’s e-mail address.
	 */
	public java.lang.String getMail() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.Users.USERS.MAIL);
	}

	/**
	 * User’s default theme.
	 */
	public void setTheme(java.lang.String value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.Users.USERS.THEME, value);
	}

	/**
	 * User’s default theme.
	 */
	public java.lang.String getTheme() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.Users.USERS.THEME);
	}

	/**
	 * User’s signature.
	 */
	public void setSignature(java.lang.String value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.Users.USERS.SIGNATURE, value);
	}

	/**
	 * User’s signature.
	 */
	public java.lang.String getSignature() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.Users.USERS.SIGNATURE);
	}

	/**
	 * The filter_format.format of the signature.
	 */
	public void setSignatureFormat(java.lang.String value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.Users.USERS.SIGNATURE_FORMAT, value);
	}

	/**
	 * The filter_format.format of the signature.
	 */
	public java.lang.String getSignatureFormat() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.Users.USERS.SIGNATURE_FORMAT);
	}

	/**
	 * Timestamp for when user was created.
	 */
	public void setCreated(java.lang.Integer value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.Users.USERS.CREATED, value);
	}

	/**
	 * Timestamp for when user was created.
	 */
	public java.lang.Integer getCreated() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.Users.USERS.CREATED);
	}

	/**
	 * Timestamp for previous time user accessed the site.
	 */
	public void setAccess(java.lang.Integer value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.Users.USERS.ACCESS, value);
	}

	/**
	 * Timestamp for previous time user accessed the site.
	 */
	public java.lang.Integer getAccess() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.Users.USERS.ACCESS);
	}

	/**
	 * Timestamp for user’s last login.
	 */
	public void setLogin(java.lang.Integer value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.Users.USERS.LOGIN, value);
	}

	/**
	 * Timestamp for user’s last login.
	 */
	public java.lang.Integer getLogin() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.Users.USERS.LOGIN);
	}

	/**
	 * Whether the user is active(1) or blocked(0).
	 */
	public void setStatus(java.lang.Byte value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.Users.USERS.STATUS, value);
	}

	/**
	 * Whether the user is active(1) or blocked(0).
	 */
	public java.lang.Byte getStatus() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.Users.USERS.STATUS);
	}

	/**
	 * User’s time zone.
	 */
	public void setTimezone(java.lang.String value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.Users.USERS.TIMEZONE, value);
	}

	/**
	 * User’s time zone.
	 */
	public java.lang.String getTimezone() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.Users.USERS.TIMEZONE);
	}

	/**
	 * User’s default language.
	 */
	public void setLanguage(java.lang.String value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.Users.USERS.LANGUAGE, value);
	}

	/**
	 * User’s default language.
	 */
	public java.lang.String getLanguage() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.Users.USERS.LANGUAGE);
	}

	/**
	 * Foreign key: file_managed.fid of user’s picture.
	 */
	public void setPicture(java.lang.Integer value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.Users.USERS.PICTURE, value);
	}

	/**
	 * Foreign key: file_managed.fid of user’s picture.
	 */
	public java.lang.Integer getPicture() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.Users.USERS.PICTURE);
	}

	/**
	 * E-mail address used for initial account creation.
	 */
	public void setInit(java.lang.String value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.Users.USERS.INIT, value);
	}

	/**
	 * E-mail address used for initial account creation.
	 */
	public java.lang.String getInit() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.Users.USERS.INIT);
	}

	/**
	 * A serialized array of name value pairs that are related to the user. Any form values posted during user edit are stored and are loaded into the $user object during user_load(). Use of this field is discouraged and it will likely disappear in a future...
	 */
	public void setData(byte[] value) {
		setValue(edu.iup.chem.inventory.db.inventory.tables.Users.USERS.DATA, value);
	}

	/**
	 * A serialized array of name value pairs that are related to the user. Any form values posted during user edit are stored and are loaded into the $user object during user_load(). Use of this field is discouraged and it will likely disappear in a future...
	 */
	public byte[] getData() {
		return getValue(edu.iup.chem.inventory.db.inventory.tables.Users.USERS.DATA);
	}

	/**
	 * Create a detached UsersRecord
	 */
	public UsersRecord() {
		super(edu.iup.chem.inventory.db.inventory.tables.Users.USERS);
	}
}
