/**
 * This class is generated by jOOQ
 */
package edu.iup.chem.inventory.db.inventory.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.1"},
                            comments = "This class is generated by jOOQ")
public class Cancer extends org.jooq.impl.TableImpl<edu.iup.chem.inventory.db.inventory.tables.records.CancerRecord> {

	private static final long serialVersionUID = 683649847;

	/**
	 * The singleton instance of inventory.cancer
	 */
	public static final edu.iup.chem.inventory.db.inventory.tables.Cancer CANCER = new edu.iup.chem.inventory.db.inventory.tables.Cancer();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<edu.iup.chem.inventory.db.inventory.tables.records.CancerRecord> getRecordType() {
		return edu.iup.chem.inventory.db.inventory.tables.records.CancerRecord.class;
	}

	/**
	 * The table column <code>inventory.cancer.name</code>
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.CancerRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>inventory.cancer.type</code>
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.CancerRecord, java.lang.String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>inventory.cancer.listing</code>
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.CancerRecord, java.lang.String> LISTING = createField("listing", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>inventory.cancer.cas</code>
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.CancerRecord, java.lang.String> CAS = createField("cas", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>inventory.cancer.date</code>
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.CancerRecord, java.lang.String> DATE = createField("date", org.jooq.impl.SQLDataType.VARCHAR, this);

	public Cancer() {
		super("cancer", edu.iup.chem.inventory.db.inventory.Inventory.INVENTORY);
	}

	public Cancer(java.lang.String alias) {
		super(alias, edu.iup.chem.inventory.db.inventory.Inventory.INVENTORY, edu.iup.chem.inventory.db.inventory.tables.Cancer.CANCER);
	}

	@Override
	public edu.iup.chem.inventory.db.inventory.tables.Cancer as(java.lang.String alias) {
		return new edu.iup.chem.inventory.db.inventory.tables.Cancer(alias);
	}
}
