/**
 * This class is generated by jOOQ
 */
package edu.iup.chem.inventory.db.inventory.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.1"},
                            comments = "This class is generated by jOOQ")
public class Chemical extends org.jooq.impl.UpdatableTableImpl<edu.iup.chem.inventory.db.inventory.tables.records.ChemicalRecord> {

	private static final long serialVersionUID = 1604504689;

	/**
	 * The singleton instance of inventory.chemical
	 */
	public static final edu.iup.chem.inventory.db.inventory.tables.Chemical CHEMICAL = new edu.iup.chem.inventory.db.inventory.tables.Chemical();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<edu.iup.chem.inventory.db.inventory.tables.records.ChemicalRecord> getRecordType() {
		return edu.iup.chem.inventory.db.inventory.tables.records.ChemicalRecord.class;
	}

	/**
	 * The table column <code>inventory.chemical.cas</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.ChemicalRecord, java.lang.String> CAS = createField("cas", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>inventory.chemical.storage_class</code>
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.ChemicalRecord, edu.iup.chem.inventory.db.inventory.enums.ChemicalStorageClass> STORAGE_CLASS = createField("storage_class", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(edu.iup.chem.inventory.db.inventory.enums.ChemicalStorageClass.class), this);

	/**
	 * The table column <code>inventory.chemical.toxic</code>
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.ChemicalRecord, edu.iup.chem.inventory.db.inventory.enums.ChemicalToxic> TOXIC = createField("toxic", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(edu.iup.chem.inventory.db.inventory.enums.ChemicalToxic.class), this);

	/**
	 * The table column <code>inventory.chemical.cold</code>
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.ChemicalRecord, edu.iup.chem.inventory.db.inventory.enums.ChemicalCold> COLD = createField("cold", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(edu.iup.chem.inventory.db.inventory.enums.ChemicalCold.class), this);

	/**
	 * The table column <code>inventory.chemical.flamm</code>
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.ChemicalRecord, edu.iup.chem.inventory.db.inventory.enums.ChemicalFlamm> FLAMM = createField("flamm", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(edu.iup.chem.inventory.db.inventory.enums.ChemicalFlamm.class), this);

	/**
	 * The table column <code>inventory.chemical.carc</code>
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.ChemicalRecord, edu.iup.chem.inventory.db.inventory.enums.ChemicalCarc> CARC = createField("carc", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(edu.iup.chem.inventory.db.inventory.enums.ChemicalCarc.class), this);

	/**
	 * The table column <code>inventory.chemical.nfpa_h</code>
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.ChemicalRecord, java.lang.Integer> NFPA_H = createField("nfpa_h", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>inventory.chemical.nfpa_f</code>
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.ChemicalRecord, java.lang.Integer> NFPA_F = createField("nfpa_f", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>inventory.chemical.nfpa_r</code>
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.ChemicalRecord, java.lang.Integer> NFPA_R = createField("nfpa_r", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>inventory.chemical.nfpa_s</code>
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.ChemicalRecord, edu.iup.chem.inventory.db.inventory.enums.ChemicalNfpaS> NFPA_S = createField("nfpa_s", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(edu.iup.chem.inventory.db.inventory.enums.ChemicalNfpaS.class), this);

	/**
	 * The table column <code>inventory.chemical.smiles</code>
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.ChemicalRecord, java.lang.String> SMILES = createField("smiles", org.jooq.impl.SQLDataType.CLOB, this);

	/**
	 * The table column <code>inventory.chemical.name</code>
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.ChemicalRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB, this);

	/**
	 * The table column <code>inventory.chemical.formula</code>
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.ChemicalRecord, java.lang.String> FORMULA = createField("formula", org.jooq.impl.SQLDataType.CLOB, this);

	/**
	 * ID for ChemSpider searches
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.ChemicalRecord, java.lang.String> CSID = createField("csid", org.jooq.impl.SQLDataType.CLOB, this);

	/**
	 * International Chemical Identifier (unique)
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.ChemicalRecord, java.lang.String> INCHI = createField("inchi", org.jooq.impl.SQLDataType.CLOB, this);

	public Chemical() {
		super("chemical", edu.iup.chem.inventory.db.inventory.Inventory.INVENTORY);
	}

	public Chemical(java.lang.String alias) {
		super(alias, edu.iup.chem.inventory.db.inventory.Inventory.INVENTORY, edu.iup.chem.inventory.db.inventory.tables.Chemical.CHEMICAL);
	}

	@Override
	public org.jooq.UniqueKey<edu.iup.chem.inventory.db.inventory.tables.records.ChemicalRecord> getMainKey() {
		return edu.iup.chem.inventory.db.inventory.Keys.KEY_CHEMICAL_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<edu.iup.chem.inventory.db.inventory.tables.records.ChemicalRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<edu.iup.chem.inventory.db.inventory.tables.records.ChemicalRecord>>asList(edu.iup.chem.inventory.db.inventory.Keys.KEY_CHEMICAL_PRIMARY);
	}

	@Override
	public edu.iup.chem.inventory.db.inventory.tables.Chemical as(java.lang.String alias) {
		return new edu.iup.chem.inventory.db.inventory.tables.Chemical(alias);
	}
}
