/**
 * This class is generated by jOOQ
 */
package edu.iup.chem.inventory.db.inventory.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.1"},
                            comments = "This class is generated by jOOQ")
public class JchempropertiesCr extends org.jooq.impl.UpdatableTableImpl<edu.iup.chem.inventory.db.inventory.tables.records.JchempropertiesCrRecord> {

	private static final long serialVersionUID = 1429941434;

	/**
	 * The singleton instance of inventory.jchemproperties_cr
	 */
	public static final edu.iup.chem.inventory.db.inventory.tables.JchempropertiesCr JCHEMPROPERTIES_CR = new edu.iup.chem.inventory.db.inventory.tables.JchempropertiesCr();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<edu.iup.chem.inventory.db.inventory.tables.records.JchempropertiesCrRecord> getRecordType() {
		return edu.iup.chem.inventory.db.inventory.tables.records.JchempropertiesCrRecord.class;
	}

	/**
	 * The table column <code>inventory.jchemproperties_cr.cache_id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.JchempropertiesCrRecord, java.lang.String> CACHE_ID = createField("cache_id", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>inventory.jchemproperties_cr.registration_time</code>
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.JchempropertiesCrRecord, java.lang.String> REGISTRATION_TIME = createField("registration_time", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>inventory.jchemproperties_cr.is_protected</code>
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.JchempropertiesCrRecord, java.lang.Byte> IS_PROTECTED = createField("is_protected", org.jooq.impl.SQLDataType.TINYINT, this);

	public JchempropertiesCr() {
		super("jchemproperties_cr", edu.iup.chem.inventory.db.inventory.Inventory.INVENTORY);
	}

	public JchempropertiesCr(java.lang.String alias) {
		super(alias, edu.iup.chem.inventory.db.inventory.Inventory.INVENTORY, edu.iup.chem.inventory.db.inventory.tables.JchempropertiesCr.JCHEMPROPERTIES_CR);
	}

	@Override
	public org.jooq.UniqueKey<edu.iup.chem.inventory.db.inventory.tables.records.JchempropertiesCrRecord> getMainKey() {
		return edu.iup.chem.inventory.db.inventory.Keys.KEY_JCHEMPROPERTIES_CR_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<edu.iup.chem.inventory.db.inventory.tables.records.JchempropertiesCrRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<edu.iup.chem.inventory.db.inventory.tables.records.JchempropertiesCrRecord>>asList(edu.iup.chem.inventory.db.inventory.Keys.KEY_JCHEMPROPERTIES_CR_PRIMARY);
	}

	@Override
	public edu.iup.chem.inventory.db.inventory.tables.JchempropertiesCr as(java.lang.String alias) {
		return new edu.iup.chem.inventory.db.inventory.tables.JchempropertiesCr(alias);
	}
}
