/**
 * This class is generated by jOOQ
 */
package edu.iup.chem.inventory.db.inventory.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.1"},
                            comments = "This class is generated by jOOQ")
public class Jchemproperties extends org.jooq.impl.UpdatableTableImpl<edu.iup.chem.inventory.db.inventory.tables.records.JchempropertiesRecord> {

	private static final long serialVersionUID = -1371510382;

	/**
	 * The singleton instance of inventory.jchemproperties
	 */
	public static final edu.iup.chem.inventory.db.inventory.tables.Jchemproperties JCHEMPROPERTIES = new edu.iup.chem.inventory.db.inventory.tables.Jchemproperties();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<edu.iup.chem.inventory.db.inventory.tables.records.JchempropertiesRecord> getRecordType() {
		return edu.iup.chem.inventory.db.inventory.tables.records.JchempropertiesRecord.class;
	}

	/**
	 * The table column <code>inventory.jchemproperties.prop_name</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.JchempropertiesRecord, java.lang.String> PROP_NAME = createField("prop_name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>inventory.jchemproperties.prop_value</code>
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.JchempropertiesRecord, java.lang.String> PROP_VALUE = createField("prop_value", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>inventory.jchemproperties.prop_value_ext</code>
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.JchempropertiesRecord, byte[]> PROP_VALUE_EXT = createField("prop_value_ext", org.jooq.impl.SQLDataType.BLOB, this);

	public Jchemproperties() {
		super("jchemproperties", edu.iup.chem.inventory.db.inventory.Inventory.INVENTORY);
	}

	public Jchemproperties(java.lang.String alias) {
		super(alias, edu.iup.chem.inventory.db.inventory.Inventory.INVENTORY, edu.iup.chem.inventory.db.inventory.tables.Jchemproperties.JCHEMPROPERTIES);
	}

	@Override
	public org.jooq.UniqueKey<edu.iup.chem.inventory.db.inventory.tables.records.JchempropertiesRecord> getMainKey() {
		return edu.iup.chem.inventory.db.inventory.Keys.KEY_JCHEMPROPERTIES_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<edu.iup.chem.inventory.db.inventory.tables.records.JchempropertiesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<edu.iup.chem.inventory.db.inventory.tables.records.JchempropertiesRecord>>asList(edu.iup.chem.inventory.db.inventory.Keys.KEY_JCHEMPROPERTIES_PRIMARY);
	}

	@Override
	public edu.iup.chem.inventory.db.inventory.tables.Jchemproperties as(java.lang.String alias) {
		return new edu.iup.chem.inventory.db.inventory.tables.Jchemproperties(alias);
	}
}
