/**
 * This class is generated by jOOQ
 */
package edu.iup.chem.inventory.db.inventory.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.1"},
                            comments = "This class is generated by jOOQ")
public class Room extends org.jooq.impl.UpdatableTableImpl<edu.iup.chem.inventory.db.inventory.tables.records.RoomRecord> {

	private static final long serialVersionUID = -543480912;

	/**
	 * The singleton instance of inventory.room
	 */
	public static final edu.iup.chem.inventory.db.inventory.tables.Room ROOM = new edu.iup.chem.inventory.db.inventory.tables.Room();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<edu.iup.chem.inventory.db.inventory.tables.records.RoomRecord> getRecordType() {
		return edu.iup.chem.inventory.db.inventory.tables.records.RoomRecord.class;
	}

	/**
	 * The table column <code>inventory.room.room</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.RoomRecord, java.lang.String> ROOM_ = createField("room", org.jooq.impl.SQLDataType.VARCHAR, this);

	public Room() {
		super("room", edu.iup.chem.inventory.db.inventory.Inventory.INVENTORY);
	}

	public Room(java.lang.String alias) {
		super(alias, edu.iup.chem.inventory.db.inventory.Inventory.INVENTORY, edu.iup.chem.inventory.db.inventory.tables.Room.ROOM);
	}

	@Override
	public org.jooq.UniqueKey<edu.iup.chem.inventory.db.inventory.tables.records.RoomRecord> getMainKey() {
		return edu.iup.chem.inventory.db.inventory.Keys.KEY_ROOM_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<edu.iup.chem.inventory.db.inventory.tables.records.RoomRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<edu.iup.chem.inventory.db.inventory.tables.records.RoomRecord>>asList(edu.iup.chem.inventory.db.inventory.Keys.KEY_ROOM_PRIMARY);
	}

	@Override
	public edu.iup.chem.inventory.db.inventory.tables.Room as(java.lang.String alias) {
		return new edu.iup.chem.inventory.db.inventory.tables.Room(alias);
	}
}
