/**
 * This class is generated by jOOQ
 */
package edu.iup.chem.inventory.db.inventory.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.1"},
                            comments = "This class is generated by jOOQ")
public class StructuresUl extends org.jooq.impl.UpdatableTableImpl<edu.iup.chem.inventory.db.inventory.tables.records.StructuresUlRecord> {

	private static final long serialVersionUID = 1419005959;

	/**
	 * The singleton instance of inventory.structures_ul
	 */
	public static final edu.iup.chem.inventory.db.inventory.tables.StructuresUl STRUCTURES_UL = new edu.iup.chem.inventory.db.inventory.tables.StructuresUl();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<edu.iup.chem.inventory.db.inventory.tables.records.StructuresUlRecord> getRecordType() {
		return edu.iup.chem.inventory.db.inventory.tables.records.StructuresUlRecord.class;
	}

	/**
	 * The table column <code>inventory.structures_ul.update_id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.StructuresUlRecord, java.lang.Integer> UPDATE_ID = createField("update_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>inventory.structures_ul.update_info</code>
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.StructuresUlRecord, java.lang.String> UPDATE_INFO = createField("update_info", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>inventory.structures_ul.cache_id</code>
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.StructuresUlRecord, java.lang.String> CACHE_ID = createField("cache_id", org.jooq.impl.SQLDataType.VARCHAR, this);

	public StructuresUl() {
		super("structures_ul", edu.iup.chem.inventory.db.inventory.Inventory.INVENTORY);
	}

	public StructuresUl(java.lang.String alias) {
		super(alias, edu.iup.chem.inventory.db.inventory.Inventory.INVENTORY, edu.iup.chem.inventory.db.inventory.tables.StructuresUl.STRUCTURES_UL);
	}

	@Override
	public org.jooq.Identity<edu.iup.chem.inventory.db.inventory.tables.records.StructuresUlRecord, java.lang.Integer> getIdentity() {
		return edu.iup.chem.inventory.db.inventory.Keys.IDENTITY_STRUCTURES_UL;
	}

	@Override
	public org.jooq.UniqueKey<edu.iup.chem.inventory.db.inventory.tables.records.StructuresUlRecord> getMainKey() {
		return edu.iup.chem.inventory.db.inventory.Keys.KEY_STRUCTURES_UL_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<edu.iup.chem.inventory.db.inventory.tables.records.StructuresUlRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<edu.iup.chem.inventory.db.inventory.tables.records.StructuresUlRecord>>asList(edu.iup.chem.inventory.db.inventory.Keys.KEY_STRUCTURES_UL_PRIMARY);
	}

	@Override
	public edu.iup.chem.inventory.db.inventory.tables.StructuresUl as(java.lang.String alias) {
		return new edu.iup.chem.inventory.db.inventory.tables.StructuresUl(alias);
	}
}
