/**
 * This class is generated by jOOQ
 */
package edu.iup.chem.inventory.db.inventory.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.1"},
                            comments = "This class is generated by jOOQ")
public class StructTemp extends org.jooq.impl.TableImpl<edu.iup.chem.inventory.db.inventory.tables.records.StructTempRecord> {

	private static final long serialVersionUID = -1207673780;

	/**
	 * The singleton instance of inventory.struct_temp
	 */
	public static final edu.iup.chem.inventory.db.inventory.tables.StructTemp STRUCT_TEMP = new edu.iup.chem.inventory.db.inventory.tables.StructTemp();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<edu.iup.chem.inventory.db.inventory.tables.records.StructTempRecord> getRecordType() {
		return edu.iup.chem.inventory.db.inventory.tables.records.StructTempRecord.class;
	}

	/**
	 * The table column <code>inventory.struct_temp.cd_id</code>
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.StructTempRecord, java.lang.Integer> CD_ID = createField("cd_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>inventory.struct_temp.cd_structure</code>
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.StructTempRecord, byte[]> CD_STRUCTURE = createField("cd_structure", org.jooq.impl.SQLDataType.BLOB, this);

	/**
	 * The table column <code>inventory.struct_temp.cd_smiles</code>
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.StructTempRecord, java.lang.String> CD_SMILES = createField("cd_smiles", org.jooq.impl.SQLDataType.CLOB, this);

	/**
	 * The table column <code>inventory.struct_temp.cd_formula</code>
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.StructTempRecord, java.lang.String> CD_FORMULA = createField("cd_formula", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>inventory.struct_temp.cd_sortable_formula</code>
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.StructTempRecord, java.lang.String> CD_SORTABLE_FORMULA = createField("cd_sortable_formula", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>inventory.struct_temp.cd_molweight</code>
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.StructTempRecord, java.lang.Double> CD_MOLWEIGHT = createField("cd_molweight", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The table column <code>inventory.struct_temp.cd_hash</code>
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.StructTempRecord, java.lang.Integer> CD_HASH = createField("cd_hash", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>inventory.struct_temp.cd_flags</code>
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.StructTempRecord, java.lang.String> CD_FLAGS = createField("cd_flags", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>inventory.struct_temp.cd_timestamp</code>
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.StructTempRecord, java.sql.Timestamp> CD_TIMESTAMP = createField("cd_timestamp", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The table column <code>inventory.struct_temp.cd_pre_calculated</code>
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.StructTempRecord, java.lang.Byte> CD_PRE_CALCULATED = createField("cd_pre_calculated", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * The table column <code>inventory.struct_temp.cd_fp1</code>
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.StructTempRecord, java.lang.Integer> CD_FP1 = createField("cd_fp1", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>inventory.struct_temp.cd_fp2</code>
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.StructTempRecord, java.lang.Integer> CD_FP2 = createField("cd_fp2", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>inventory.struct_temp.cd_fp3</code>
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.StructTempRecord, java.lang.Integer> CD_FP3 = createField("cd_fp3", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>inventory.struct_temp.cd_fp4</code>
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.StructTempRecord, java.lang.Integer> CD_FP4 = createField("cd_fp4", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>inventory.struct_temp.cd_fp5</code>
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.StructTempRecord, java.lang.Integer> CD_FP5 = createField("cd_fp5", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>inventory.struct_temp.cd_fp6</code>
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.StructTempRecord, java.lang.Integer> CD_FP6 = createField("cd_fp6", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>inventory.struct_temp.cd_fp7</code>
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.StructTempRecord, java.lang.Integer> CD_FP7 = createField("cd_fp7", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>inventory.struct_temp.cd_fp8</code>
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.StructTempRecord, java.lang.Integer> CD_FP8 = createField("cd_fp8", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>inventory.struct_temp.cd_fp9</code>
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.StructTempRecord, java.lang.Integer> CD_FP9 = createField("cd_fp9", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>inventory.struct_temp.cd_fp10</code>
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.StructTempRecord, java.lang.Integer> CD_FP10 = createField("cd_fp10", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>inventory.struct_temp.cd_fp11</code>
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.StructTempRecord, java.lang.Integer> CD_FP11 = createField("cd_fp11", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>inventory.struct_temp.cd_fp12</code>
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.StructTempRecord, java.lang.Integer> CD_FP12 = createField("cd_fp12", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>inventory.struct_temp.cd_fp13</code>
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.StructTempRecord, java.lang.Integer> CD_FP13 = createField("cd_fp13", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>inventory.struct_temp.cd_fp14</code>
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.StructTempRecord, java.lang.Integer> CD_FP14 = createField("cd_fp14", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>inventory.struct_temp.cd_fp15</code>
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.StructTempRecord, java.lang.Integer> CD_FP15 = createField("cd_fp15", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>inventory.struct_temp.cd_fp16</code>
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.StructTempRecord, java.lang.Integer> CD_FP16 = createField("cd_fp16", org.jooq.impl.SQLDataType.INTEGER, this);

	public StructTemp() {
		super("struct_temp", edu.iup.chem.inventory.db.inventory.Inventory.INVENTORY);
	}

	public StructTemp(java.lang.String alias) {
		super(alias, edu.iup.chem.inventory.db.inventory.Inventory.INVENTORY, edu.iup.chem.inventory.db.inventory.tables.StructTemp.STRUCT_TEMP);
	}

	@Override
	public edu.iup.chem.inventory.db.inventory.tables.StructTemp as(java.lang.String alias) {
		return new edu.iup.chem.inventory.db.inventory.tables.StructTemp(alias);
	}
}
