/**
 * This class is generated by jOOQ
 */
package edu.iup.chem.inventory.db.inventory.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.1"},
                            comments = "This class is generated by jOOQ")
public class Synonym extends org.jooq.impl.UpdatableTableImpl<edu.iup.chem.inventory.db.inventory.tables.records.SynonymRecord> {

	private static final long serialVersionUID = 1552432035;

	/**
	 * The singleton instance of inventory.synonym
	 */
	public static final edu.iup.chem.inventory.db.inventory.tables.Synonym SYNONYM = new edu.iup.chem.inventory.db.inventory.tables.Synonym();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<edu.iup.chem.inventory.db.inventory.tables.records.SynonymRecord> getRecordType() {
		return edu.iup.chem.inventory.db.inventory.tables.records.SynonymRecord.class;
	}

	/**
	 * The table column <code>inventory.synonym.cas</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.SynonymRecord, java.lang.String> CAS = createField("cas", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>inventory.synonym.names</code>
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.SynonymRecord, java.lang.String> NAMES = createField("names", org.jooq.impl.SQLDataType.CLOB, this);

	public Synonym() {
		super("synonym", edu.iup.chem.inventory.db.inventory.Inventory.INVENTORY);
	}

	public Synonym(java.lang.String alias) {
		super(alias, edu.iup.chem.inventory.db.inventory.Inventory.INVENTORY, edu.iup.chem.inventory.db.inventory.tables.Synonym.SYNONYM);
	}

	@Override
	public org.jooq.UniqueKey<edu.iup.chem.inventory.db.inventory.tables.records.SynonymRecord> getMainKey() {
		return edu.iup.chem.inventory.db.inventory.Keys.KEY_SYNONYM_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<edu.iup.chem.inventory.db.inventory.tables.records.SynonymRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<edu.iup.chem.inventory.db.inventory.tables.records.SynonymRecord>>asList(edu.iup.chem.inventory.db.inventory.Keys.KEY_SYNONYM_PRIMARY);
	}

	@Override
	public edu.iup.chem.inventory.db.inventory.tables.Synonym as(java.lang.String alias) {
		return new edu.iup.chem.inventory.db.inventory.tables.Synonym(alias);
	}
}
