/**
 * This class is generated by jOOQ
 */
package edu.iup.chem.inventory.db.inventory.tables;

/**
 * This class is generated by jOOQ.
 *
 * Stores user data.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.1"},
                            comments = "This class is generated by jOOQ")
public class Users extends org.jooq.impl.UpdatableTableImpl<edu.iup.chem.inventory.db.inventory.tables.records.UsersRecord> {

	private static final long serialVersionUID = -443425882;

	/**
	 * The singleton instance of inventory.users
	 */
	public static final edu.iup.chem.inventory.db.inventory.tables.Users USERS = new edu.iup.chem.inventory.db.inventory.tables.Users();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<edu.iup.chem.inventory.db.inventory.tables.records.UsersRecord> getRecordType() {
		return edu.iup.chem.inventory.db.inventory.tables.records.UsersRecord.class;
	}

	/**
	 * Primary Key: Unique user ID.
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.UsersRecord, org.jooq.tools.unsigned.UInteger> UID = createField("uid", org.jooq.impl.SQLDataType.INTEGERUNSIGNED, this);

	/**
	 * Unique user name.
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.UsersRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * User’s password (hashed).
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.UsersRecord, java.lang.String> PASS = createField("pass", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * User’s e-mail address.
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.UsersRecord, java.lang.String> MAIL = createField("mail", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * User’s default theme.
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.UsersRecord, java.lang.String> THEME = createField("theme", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * User’s signature.
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.UsersRecord, java.lang.String> SIGNATURE = createField("signature", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The filter_format.format of the signature.
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.UsersRecord, java.lang.String> SIGNATURE_FORMAT = createField("signature_format", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * Timestamp for when user was created.
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.UsersRecord, java.lang.Integer> CREATED = createField("created", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * Timestamp for previous time user accessed the site.
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.UsersRecord, java.lang.Integer> ACCESS = createField("access", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * Timestamp for user’s last login.
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.UsersRecord, java.lang.Integer> LOGIN = createField("login", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * Whether the user is active(1) or blocked(0).
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.UsersRecord, java.lang.Byte> STATUS = createField("status", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * User’s time zone.
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.UsersRecord, java.lang.String> TIMEZONE = createField("timezone", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * User’s default language.
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.UsersRecord, java.lang.String> LANGUAGE = createField("language", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * Foreign key: file_managed.fid of user’s picture.
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.UsersRecord, java.lang.Integer> PICTURE = createField("picture", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * E-mail address used for initial account creation.
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.UsersRecord, java.lang.String> INIT = createField("init", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * A serialized array of name value pairs that are related to the user. Any form values posted during user edit are stored and are loaded into the $user object during user_load(). Use of this field is discouraged and it will likely disappear in a future...
	 */
	public final org.jooq.TableField<edu.iup.chem.inventory.db.inventory.tables.records.UsersRecord, byte[]> DATA = createField("data", org.jooq.impl.SQLDataType.BLOB, this);

	public Users() {
		super("users", edu.iup.chem.inventory.db.inventory.Inventory.INVENTORY);
	}

	public Users(java.lang.String alias) {
		super(alias, edu.iup.chem.inventory.db.inventory.Inventory.INVENTORY, edu.iup.chem.inventory.db.inventory.tables.Users.USERS);
	}

	@Override
	public org.jooq.UniqueKey<edu.iup.chem.inventory.db.inventory.tables.records.UsersRecord> getMainKey() {
		return edu.iup.chem.inventory.db.inventory.Keys.KEY_USERS_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<edu.iup.chem.inventory.db.inventory.tables.records.UsersRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<edu.iup.chem.inventory.db.inventory.tables.records.UsersRecord>>asList(edu.iup.chem.inventory.db.inventory.Keys.KEY_USERS_PRIMARY, edu.iup.chem.inventory.db.inventory.Keys.KEY_USERS_NAME);
	}

	@Override
	public edu.iup.chem.inventory.db.inventory.tables.Users as(java.lang.String alias) {
		return new edu.iup.chem.inventory.db.inventory.tables.Users(alias);
	}
}
