/**
 * This class is generated by jOOQ
 */
package edu.iup.chem.inventory.db.inventory.enums;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.1"},
                            comments = "This class is generated by jOOQ")
public enum ChemicalToxic implements org.jooq.EnumType {
	Extremely_toxic("Extremely toxic"),

	Highly_toxic("Highly toxic"),

	Moderately_toxic("Moderately toxic"),

	Slightly_toxic("Slightly toxic"),

	Practically_nontoxic("Practically nontoxic"),

	;

	private final java.lang.String literal;

	private ChemicalToxic(java.lang.String literal) {
		this.literal = literal;
	}

	@Override
	public java.lang.String getName() {
		return "chemical_toxic";
	}

	@Override
	public java.lang.String getLiteral() {
		return literal;
	}
}
