/**
 * This class is generated by jOOQ
 */
package edu.iup.chem.inventory.db.inventory.enums;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.1"},
                            comments = "This class is generated by jOOQ")
public enum ChemicalStorageClass implements org.jooq.EnumType {
	Flammable("Flammable"),

	Peroxide_Formers("Peroxide Formers"),

	Pyrophoric_Materials("Pyrophoric Materials"),

	Explosives("Explosives"),

	Oxidizers("Oxidizers"),

	Organic_Peroxides("Organic Peroxides"),

	Radioactive("Radioactive"),

	Inorganic_Acids("Inorganic Acids"),

	Organic_Acids("Organic Acids"),

	Inorganic_Bases("Inorganic Bases"),

	Organic_Base("Organic Base"),

	Highly_Toxic("Highly Toxic"),

	Low_Hazard("Low Hazard"),

	;

	private final java.lang.String literal;

	private ChemicalStorageClass(java.lang.String literal) {
		this.literal = literal;
	}

	@Override
	public java.lang.String getName() {
		return "chemical_storage_class";
	}

	@Override
	public java.lang.String getLiteral() {
		return literal;
	}
}
