/**
 * This class is generated by jOOQ
 */
package edu.iup.chem.inventory.db.inventory.enums;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.5.1"},
                            comments = "This class is generated by jOOQ")
public enum ChemicalFlamm implements org.jooq.EnumType {
	No("No"),

	Yes("Yes"),

	;

	private final java.lang.String literal;

	private ChemicalFlamm(java.lang.String literal) {
		this.literal = literal;
	}

	@Override
	public java.lang.String getName() {
		return "chemical_flamm";
	}

	@Override
	public java.lang.String getLiteral() {
		return literal;
	}
}
