/**
 * This class is generated by jOOQ
 */
package edu.iup.chem.inventory.db.inventory.enums;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value = { "http://www.jooq.org", "2.5.1" }, comments = "This class is generated by jOOQ")
public enum ChemicalToxic implements org.jooq.EnumType {
	Extremely_toxic("Extremely toxic"),

	Highly_toxic("Highly toxic"),

	Moderately_toxic("Moderately toxic"),

	Slightly_toxic("Slightly toxic"),

	Practically_nontoxic("Practically nontoxic"),

	Unknown("Unknown"),

	;

	private final java.lang.String	literal;

	private ChemicalToxic(final java.lang.String literal) {
		this.literal = literal;
	}

	public String getDescription() {

		switch (literal) {
			case "Extremely toxic":
				return "A taste (less than 7 drops)";
			case "Highly toxic":
				return "Between 7 drops and 1 teaspoonful";
			case "Moderately toxic":
				return "Between 1 teaspoonful and 1 ounce";
			case "Slightly toxic":
				return "Between 1 ounce and 1 pint";
			case "Practically nontoxic":
				return "More than 1 pint";
			default:
				return "Unknown";
		}
	}

	@Override
	public java.lang.String getLiteral() {
		return literal;
	}

	@Override
	public java.lang.String getName() {
		return "chemical_toxic";
	}
}
