/**
 * This class is generated by jOOQ
 */
package edu.iup.chem.inventory.db.inventory.enums;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value = { "http://www.jooq.org", "2.5.1" }, comments = "This class is generated by jOOQ")
public enum ChemicalStorageClass implements org.jooq.EnumType {
	Organic_base("Organic Base"), Water_reactive("Water Reactive"), Inorganic_base(
			"Inorganic Base"), Organic_acids("Organic Acids"), Oxidizers(
			"Oxidizers"), Inorganic_acids("Inorganic Acids"), Aromatics(
			"Aromatics"), Cyanohydrins("Cyanohydrins"), Alcohols("Alcohols"), Flammables(
			"Flammables"), Non_reactive_gas("Non-reactive Gas"), Reactive_gas(
			"Reactive Gas"), Biomedical("Biomedical"), Radioactive(
			"Radioactive"), Incompatible("Incompatible"), Low_hazard(
			"Low Hazard"), Unknown("Unknown"),

	;

	public static String getClassLetter(final String literal2) {
		String letter = null;
		switch (literal2) {
			case "Organic Base":
				letter = "A";
				break;
			case "Water Reactive":
				letter = "B";
				break;
			case "Inorganic Base":
				letter = "C";
				break;
			case "Organic Acids":
				letter = "D";
				break;
			case "Oxidizers":
				letter = "E";
				break;
			case "Inorganic Acids":
				letter = "F";
				break;
			case "Aromatics":
				letter = "G";
				break;
			case "Cyanohydrins":
				letter = "H";
				break;
			case "Alcohols":
				letter = "I";
				break;
			case "Flammables":
				letter = "J";
				break;
			case "Non-reactive Gas":
				letter = "K";
				break;
			case "Reactive Gas":
				letter = "L";
				break;
			case "Biomedical":
				letter = "M";
				break;
			case "Radioactive":
				letter = "N";
				break;
			case "Incompatible":
				letter = "X";
				break;
			case "Low Hazard":
				letter = "O";
				break;
			default:
				letter = "U";
				break;
		}

		return letter;
	}

	private final java.lang.String	literal;

	private ChemicalStorageClass(final java.lang.String literal) {
		this.literal = literal;
	}

	public String getClassLetter() {
		String letter = null;
		switch (literal) {
			case "Organic Base":
				letter = "A";
				break;
			case "Water Reactive":
				letter = "B";
				break;
			case "Inorganic Base":
				letter = "C";
				break;
			case "Organic Acids":
				letter = "D";
				break;
			case "Oxidizers":
				letter = "E";
				break;
			case "Inorganic Acids":
				letter = "F";
				break;
			case "Aromatics":
				letter = "G";
				break;
			case "Cyanohydrins":
				letter = "H";
				break;
			case "Alcohols":
				letter = "I";
				break;
			case "Flammables":
				letter = "J";
				break;
			case "Non-reactive Gas":
				letter = "K";
				break;
			case "Reactive Gas":
				letter = "L";
				break;
			case "Biomedical":
				letter = "M";
				break;
			case "Radioactive":
				letter = "N";
				break;
			case "Incompatible":
				letter = "X";
				break;
			case "Low Hazard":
				letter = "O";
				break;
			default:
				letter = "U";
				break;
		}

		return letter;
	}

	@Override
	public java.lang.String getLiteral() {
		return literal;
	}

	@Override
	public java.lang.String getName() {
		return "chemical_storage_class";
	}
}
